// Code generated by ent, DO NOT EDIT.

package userprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userprofile type in the database.
	Label = "user_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "user_id"
	// FieldFullName holds the string denoting the full_name field in the database.
	FieldFullName = "full_name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldJobTitle holds the string denoting the job_title field in the database.
	FieldJobTitle = "job_title"
	// FieldSystemRole holds the string denoting the system_role field in the database.
	FieldSystemRole = "system_role"
	// FieldPinHash holds the string denoting the pin_hash field in the database.
	FieldPinHash = "pin_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the userprofile in the database.
	Table = "user_profiles"
)

// Columns holds all SQL columns for userprofile fields.
var Columns = []string{
	FieldID,
	FieldFullName,
	FieldPhone,
	FieldJobTitle,
	FieldSystemRole,
	FieldPinHash,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSystemRole holds the default value on creation for the "system_role" field.
	DefaultSystemRole string
	// DefaultPinHash holds the default value on creation for the "pin_hash" field.
	DefaultPinHash string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFullName orders the results by the full_name field.
func ByFullName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullName, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByJobTitle orders the results by the job_title field.
func ByJobTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobTitle, opts...).ToFunc()
}

// BySystemRole orders the results by the system_role field.
func BySystemRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemRole, opts...).ToFunc()
}

// ByPinHash orders the results by the pin_hash field.
func ByPinHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
