// Code generated by ent, DO NOT EDIT.

package userprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldID, id))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldFullName, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPhone, v))
}

// JobTitle applies equality check predicate on the "job_title" field. It's identical to JobTitleEQ.
func JobTitle(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldJobTitle, v))
}

// SystemRole applies equality check predicate on the "system_role" field. It's identical to SystemRoleEQ.
func SystemRole(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSystemRole, v))
}

// PinHash applies equality check predicate on the "pin_hash" field. It's identical to PinHashEQ.
func PinHash(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPinHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldFullName, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldPhone, v))
}

// JobTitleEQ applies the EQ predicate on the "job_title" field.
func JobTitleEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldJobTitle, v))
}

// JobTitleNEQ applies the NEQ predicate on the "job_title" field.
func JobTitleNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldJobTitle, v))
}

// JobTitleIn applies the In predicate on the "job_title" field.
func JobTitleIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldJobTitle, vs...))
}

// JobTitleNotIn applies the NotIn predicate on the "job_title" field.
func JobTitleNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldJobTitle, vs...))
}

// JobTitleGT applies the GT predicate on the "job_title" field.
func JobTitleGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldJobTitle, v))
}

// JobTitleGTE applies the GTE predicate on the "job_title" field.
func JobTitleGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldJobTitle, v))
}

// JobTitleLT applies the LT predicate on the "job_title" field.
func JobTitleLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldJobTitle, v))
}

// JobTitleLTE applies the LTE predicate on the "job_title" field.
func JobTitleLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldJobTitle, v))
}

// JobTitleContains applies the Contains predicate on the "job_title" field.
func JobTitleContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldJobTitle, v))
}

// JobTitleHasPrefix applies the HasPrefix predicate on the "job_title" field.
func JobTitleHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldJobTitle, v))
}

// JobTitleHasSuffix applies the HasSuffix predicate on the "job_title" field.
func JobTitleHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldJobTitle, v))
}

// JobTitleIsNil applies the IsNil predicate on the "job_title" field.
func JobTitleIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldJobTitle))
}

// JobTitleNotNil applies the NotNil predicate on the "job_title" field.
func JobTitleNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldJobTitle))
}

// JobTitleEqualFold applies the EqualFold predicate on the "job_title" field.
func JobTitleEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldJobTitle, v))
}

// JobTitleContainsFold applies the ContainsFold predicate on the "job_title" field.
func JobTitleContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldJobTitle, v))
}

// SystemRoleEQ applies the EQ predicate on the "system_role" field.
func SystemRoleEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldSystemRole, v))
}

// SystemRoleNEQ applies the NEQ predicate on the "system_role" field.
func SystemRoleNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldSystemRole, v))
}

// SystemRoleIn applies the In predicate on the "system_role" field.
func SystemRoleIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldSystemRole, vs...))
}

// SystemRoleNotIn applies the NotIn predicate on the "system_role" field.
func SystemRoleNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldSystemRole, vs...))
}

// SystemRoleGT applies the GT predicate on the "system_role" field.
func SystemRoleGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldSystemRole, v))
}

// SystemRoleGTE applies the GTE predicate on the "system_role" field.
func SystemRoleGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldSystemRole, v))
}

// SystemRoleLT applies the LT predicate on the "system_role" field.
func SystemRoleLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldSystemRole, v))
}

// SystemRoleLTE applies the LTE predicate on the "system_role" field.
func SystemRoleLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldSystemRole, v))
}

// SystemRoleContains applies the Contains predicate on the "system_role" field.
func SystemRoleContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldSystemRole, v))
}

// SystemRoleHasPrefix applies the HasPrefix predicate on the "system_role" field.
func SystemRoleHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldSystemRole, v))
}

// SystemRoleHasSuffix applies the HasSuffix predicate on the "system_role" field.
func SystemRoleHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldSystemRole, v))
}

// SystemRoleEqualFold applies the EqualFold predicate on the "system_role" field.
func SystemRoleEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldSystemRole, v))
}

// SystemRoleContainsFold applies the ContainsFold predicate on the "system_role" field.
func SystemRoleContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldSystemRole, v))
}

// PinHashEQ applies the EQ predicate on the "pin_hash" field.
func PinHashEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldPinHash, v))
}

// PinHashNEQ applies the NEQ predicate on the "pin_hash" field.
func PinHashNEQ(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldPinHash, v))
}

// PinHashIn applies the In predicate on the "pin_hash" field.
func PinHashIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldPinHash, vs...))
}

// PinHashNotIn applies the NotIn predicate on the "pin_hash" field.
func PinHashNotIn(vs ...string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldPinHash, vs...))
}

// PinHashGT applies the GT predicate on the "pin_hash" field.
func PinHashGT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldPinHash, v))
}

// PinHashGTE applies the GTE predicate on the "pin_hash" field.
func PinHashGTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldPinHash, v))
}

// PinHashLT applies the LT predicate on the "pin_hash" field.
func PinHashLT(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldPinHash, v))
}

// PinHashLTE applies the LTE predicate on the "pin_hash" field.
func PinHashLTE(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldPinHash, v))
}

// PinHashContains applies the Contains predicate on the "pin_hash" field.
func PinHashContains(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContains(FieldPinHash, v))
}

// PinHashHasPrefix applies the HasPrefix predicate on the "pin_hash" field.
func PinHashHasPrefix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasPrefix(FieldPinHash, v))
}

// PinHashHasSuffix applies the HasSuffix predicate on the "pin_hash" field.
func PinHashHasSuffix(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldHasSuffix(FieldPinHash, v))
}

// PinHashIsNil applies the IsNil predicate on the "pin_hash" field.
func PinHashIsNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIsNull(FieldPinHash))
}

// PinHashNotNil applies the NotNil predicate on the "pin_hash" field.
func PinHashNotNil() predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotNull(FieldPinHash))
}

// PinHashEqualFold applies the EqualFold predicate on the "pin_hash" field.
func PinHashEqualFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEqualFold(FieldPinHash, v))
}

// PinHashContainsFold applies the ContainsFold predicate on the "pin_hash" field.
func PinHashContainsFold(v string) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldContainsFold(FieldPinHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserProfile {
	return predicate.UserProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserProfile) predicate.UserProfile {
	return predicate.UserProfile(sql.NotPredicates(p))
}
