// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PluginInstallsColumns holds the columns for the "plugin_installs" table.
	PluginInstallsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "plugin_name", Type: field.TypeString},
		{Name: "installed_at", Type: field.TypeTime},
		{Name: "permissions", Type: field.TypeJSON, Nullable: true},
		{Name: "tenant_id", Type: field.TypeString},
	}
	// PluginInstallsTable holds the schema information for the "plugin_installs" table.
	PluginInstallsTable = &schema.Table{
		Name:       "plugin_installs",
		Columns:    PluginInstallsColumns,
		PrimaryKey: []*schema.Column{PluginInstallsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "plugin_installs_tenants_plugin_installs",
				Columns:    []*schema.Column{PluginInstallsColumns[4]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PluginMigrationHistoriesColumns holds the columns for the "plugin_migration_histories" table.
	PluginMigrationHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "plugin_name", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "applied"},
		{Name: "applied_at", Type: field.TypeTime},
	}
	// PluginMigrationHistoriesTable holds the schema information for the "plugin_migration_histories" table.
	PluginMigrationHistoriesTable = &schema.Table{
		Name:       "plugin_migration_histories",
		Columns:    PluginMigrationHistoriesColumns,
		PrimaryKey: []*schema.Column{PluginMigrationHistoriesColumns[0]},
	}
	// RefreshTokensColumns holds the columns for the "refresh_tokens" table.
	RefreshTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RefreshTokensTable holds the schema information for the "refresh_tokens" table.
	RefreshTokensTable = &schema.Table{
		Name:       "refresh_tokens",
		Columns:    RefreshTokensColumns,
		PrimaryKey: []*schema.Column{RefreshTokensColumns[0]},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "plan", Type: field.TypeString, Default: "starter"},
		{Name: "status", Type: field.TypeString, Default: "provisioning"},
		{Name: "schema_name", Type: field.TypeString, Unique: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// TenantUsersColumns holds the columns for the "tenant_users" table.
	TenantUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "role", Type: field.TypeString, Default: "member"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// TenantUsersTable holds the schema information for the "tenant_users" table.
	TenantUsersTable = &schema.Table{
		Name:       "tenant_users",
		Columns:    TenantUsersColumns,
		PrimaryKey: []*schema.Column{TenantUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenant_users_tenants_tenant_users",
				Columns:    []*schema.Column{TenantUsersColumns[3]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tenant_users_users_tenant_users",
				Columns:    []*schema.Column{TenantUsersColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tenantuser_user_id_tenant_id",
				Unique:  true,
				Columns: []*schema.Column{TenantUsersColumns[4], TenantUsersColumns[3]},
			},
			{
				Name:    "tenantuser_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TenantUsersColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "is_platform_admin", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserProfilesColumns holds the columns for the "user_profiles" table.
	UserProfilesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "job_title", Type: field.TypeString, Nullable: true},
		{Name: "system_role", Type: field.TypeString, Default: "customer"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UserProfilesTable holds the schema information for the "user_profiles" table.
	UserProfilesTable = &schema.Table{
		Name:       "user_profiles",
		Columns:    UserProfilesColumns,
		PrimaryKey: []*schema.Column{UserProfilesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PluginInstallsTable,
		PluginMigrationHistoriesTable,
		RefreshTokensTable,
		TenantsTable,
		TenantUsersTable,
		UsersTable,
		UserProfilesTable,
	}
)

func init() {
	PluginInstallsTable.ForeignKeys[0].RefTable = TenantsTable
	TenantUsersTable.ForeignKeys[0].RefTable = TenantsTable
	TenantUsersTable.ForeignKeys[1].RefTable = UsersTable
}
