// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/branch"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
)

// BranchUpdate is the builder for updating Branch entities.
type BranchUpdate struct {
	config
	hooks    []Hook
	mutation *BranchMutation
}

// Where appends a list predicates to the BranchUpdate builder.
func (bu *BranchUpdate) Where(ps ...predicate.Branch) *BranchUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetTenantID sets the "tenant_id" field.
func (bu *BranchUpdate) SetTenantID(s string) *BranchUpdate {
	bu.mutation.SetTenantID(s)
	return bu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (bu *BranchUpdate) SetNillableTenantID(s *string) *BranchUpdate {
	if s != nil {
		bu.SetTenantID(*s)
	}
	return bu
}

// SetSlug sets the "slug" field.
func (bu *BranchUpdate) SetSlug(s string) *BranchUpdate {
	bu.mutation.SetSlug(s)
	return bu
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (bu *BranchUpdate) SetNillableSlug(s *string) *BranchUpdate {
	if s != nil {
		bu.SetSlug(*s)
	}
	return bu
}

// SetName sets the "name" field.
func (bu *BranchUpdate) SetName(s string) *BranchUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bu *BranchUpdate) SetNillableName(s *string) *BranchUpdate {
	if s != nil {
		bu.SetName(*s)
	}
	return bu
}

// SetStatus sets the "status" field.
func (bu *BranchUpdate) SetStatus(s string) *BranchUpdate {
	bu.mutation.SetStatus(s)
	return bu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bu *BranchUpdate) SetNillableStatus(s *string) *BranchUpdate {
	if s != nil {
		bu.SetStatus(*s)
	}
	return bu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (bu *BranchUpdate) SetTenant(t *Tenant) *BranchUpdate {
	return bu.SetTenantID(t.ID)
}

// Mutation returns the BranchMutation object of the builder.
func (bu *BranchUpdate) Mutation() *BranchMutation {
	return bu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (bu *BranchUpdate) ClearTenant() *BranchUpdate {
	bu.mutation.ClearTenant()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BranchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BranchUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BranchUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BranchUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BranchUpdate) check() error {
	if bu.mutation.TenantCleared() && len(bu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Branch.tenant"`)
	}
	return nil
}

func (bu *BranchUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(branch.Table, branch.Columns, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeString))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Slug(); ok {
		_spec.SetField(branch.FieldSlug, field.TypeString, value)
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
	}
	if value, ok := bu.mutation.Status(); ok {
		_spec.SetField(branch.FieldStatus, field.TypeString, value)
	}
	if bu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   branch.TenantTable,
			Columns: []string{branch.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = bu.schemaConfig.Branch
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   branch.TenantTable,
			Columns: []string{branch.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = bu.schemaConfig.Branch
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = bu.schemaConfig.Branch
	ctx = internal.NewSchemaConfigContext(ctx, bu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BranchUpdateOne is the builder for updating a single Branch entity.
type BranchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BranchMutation
}

// SetTenantID sets the "tenant_id" field.
func (buo *BranchUpdateOne) SetTenantID(s string) *BranchUpdateOne {
	buo.mutation.SetTenantID(s)
	return buo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (buo *BranchUpdateOne) SetNillableTenantID(s *string) *BranchUpdateOne {
	if s != nil {
		buo.SetTenantID(*s)
	}
	return buo
}

// SetSlug sets the "slug" field.
func (buo *BranchUpdateOne) SetSlug(s string) *BranchUpdateOne {
	buo.mutation.SetSlug(s)
	return buo
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (buo *BranchUpdateOne) SetNillableSlug(s *string) *BranchUpdateOne {
	if s != nil {
		buo.SetSlug(*s)
	}
	return buo
}

// SetName sets the "name" field.
func (buo *BranchUpdateOne) SetName(s string) *BranchUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (buo *BranchUpdateOne) SetNillableName(s *string) *BranchUpdateOne {
	if s != nil {
		buo.SetName(*s)
	}
	return buo
}

// SetStatus sets the "status" field.
func (buo *BranchUpdateOne) SetStatus(s string) *BranchUpdateOne {
	buo.mutation.SetStatus(s)
	return buo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (buo *BranchUpdateOne) SetNillableStatus(s *string) *BranchUpdateOne {
	if s != nil {
		buo.SetStatus(*s)
	}
	return buo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (buo *BranchUpdateOne) SetTenant(t *Tenant) *BranchUpdateOne {
	return buo.SetTenantID(t.ID)
}

// Mutation returns the BranchMutation object of the builder.
func (buo *BranchUpdateOne) Mutation() *BranchMutation {
	return buo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (buo *BranchUpdateOne) ClearTenant() *BranchUpdateOne {
	buo.mutation.ClearTenant()
	return buo
}

// Where appends a list predicates to the BranchUpdate builder.
func (buo *BranchUpdateOne) Where(ps ...predicate.Branch) *BranchUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BranchUpdateOne) Select(field string, fields ...string) *BranchUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Branch entity.
func (buo *BranchUpdateOne) Save(ctx context.Context) (*Branch, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BranchUpdateOne) SaveX(ctx context.Context) *Branch {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BranchUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BranchUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BranchUpdateOne) check() error {
	if buo.mutation.TenantCleared() && len(buo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Branch.tenant"`)
	}
	return nil
}

func (buo *BranchUpdateOne) sqlSave(ctx context.Context) (_node *Branch, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(branch.Table, branch.Columns, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeString))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Branch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, branch.FieldID)
		for _, f := range fields {
			if !branch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != branch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Slug(); ok {
		_spec.SetField(branch.FieldSlug, field.TypeString, value)
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
	}
	if value, ok := buo.mutation.Status(); ok {
		_spec.SetField(branch.FieldStatus, field.TypeString, value)
	}
	if buo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   branch.TenantTable,
			Columns: []string{branch.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = buo.schemaConfig.Branch
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   branch.TenantTable,
			Columns: []string{branch.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = buo.schemaConfig.Branch
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = buo.schemaConfig.Branch
	ctx = internal.NewSchemaConfigContext(ctx, buo.schemaConfig)
	_node = &Branch{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
