// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/devicetoken"
)

// DeviceTokenCreate is the builder for creating a DeviceToken entity.
type DeviceTokenCreate struct {
	config
	mutation *DeviceTokenMutation
	hooks    []Hook
}

// SetTokenHash sets the "token_hash" field.
func (dtc *DeviceTokenCreate) SetTokenHash(s string) *DeviceTokenCreate {
	dtc.mutation.SetTokenHash(s)
	return dtc
}

// SetUserID sets the "user_id" field.
func (dtc *DeviceTokenCreate) SetUserID(s string) *DeviceTokenCreate {
	dtc.mutation.SetUserID(s)
	return dtc
}

// SetTenantID sets the "tenant_id" field.
func (dtc *DeviceTokenCreate) SetTenantID(s string) *DeviceTokenCreate {
	dtc.mutation.SetTenantID(s)
	return dtc
}

// SetBranchID sets the "branch_id" field.
func (dtc *DeviceTokenCreate) SetBranchID(s string) *DeviceTokenCreate {
	dtc.mutation.SetBranchID(s)
	return dtc
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableBranchID(s *string) *DeviceTokenCreate {
	if s != nil {
		dtc.SetBranchID(*s)
	}
	return dtc
}

// SetDeviceName sets the "device_name" field.
func (dtc *DeviceTokenCreate) SetDeviceName(s string) *DeviceTokenCreate {
	dtc.mutation.SetDeviceName(s)
	return dtc
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableDeviceName(s *string) *DeviceTokenCreate {
	if s != nil {
		dtc.SetDeviceName(*s)
	}
	return dtc
}

// SetCreatedAt sets the "created_at" field.
func (dtc *DeviceTokenCreate) SetCreatedAt(t time.Time) *DeviceTokenCreate {
	dtc.mutation.SetCreatedAt(t)
	return dtc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableCreatedAt(t *time.Time) *DeviceTokenCreate {
	if t != nil {
		dtc.SetCreatedAt(*t)
	}
	return dtc
}

// SetLastUsedAt sets the "last_used_at" field.
func (dtc *DeviceTokenCreate) SetLastUsedAt(t time.Time) *DeviceTokenCreate {
	dtc.mutation.SetLastUsedAt(t)
	return dtc
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableLastUsedAt(t *time.Time) *DeviceTokenCreate {
	if t != nil {
		dtc.SetLastUsedAt(*t)
	}
	return dtc
}

// SetRevokedAt sets the "revoked_at" field.
func (dtc *DeviceTokenCreate) SetRevokedAt(t time.Time) *DeviceTokenCreate {
	dtc.mutation.SetRevokedAt(t)
	return dtc
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (dtc *DeviceTokenCreate) SetNillableRevokedAt(t *time.Time) *DeviceTokenCreate {
	if t != nil {
		dtc.SetRevokedAt(*t)
	}
	return dtc
}

// SetID sets the "id" field.
func (dtc *DeviceTokenCreate) SetID(s string) *DeviceTokenCreate {
	dtc.mutation.SetID(s)
	return dtc
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (dtc *DeviceTokenCreate) Mutation() *DeviceTokenMutation {
	return dtc.mutation
}

// Save creates the DeviceToken in the database.
func (dtc *DeviceTokenCreate) Save(ctx context.Context) (*DeviceToken, error) {
	dtc.defaults()
	return withHooks(ctx, dtc.sqlSave, dtc.mutation, dtc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dtc *DeviceTokenCreate) SaveX(ctx context.Context) *DeviceToken {
	v, err := dtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtc *DeviceTokenCreate) Exec(ctx context.Context) error {
	_, err := dtc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtc *DeviceTokenCreate) ExecX(ctx context.Context) {
	if err := dtc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dtc *DeviceTokenCreate) defaults() {
	if _, ok := dtc.mutation.DeviceName(); !ok {
		v := devicetoken.DefaultDeviceName
		dtc.mutation.SetDeviceName(v)
	}
	if _, ok := dtc.mutation.CreatedAt(); !ok {
		v := devicetoken.DefaultCreatedAt()
		dtc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dtc *DeviceTokenCreate) check() error {
	if _, ok := dtc.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "DeviceToken.token_hash"`)}
	}
	if v, ok := dtc.mutation.TokenHash(); ok {
		if err := devicetoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.token_hash": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DeviceToken.user_id"`)}
	}
	if v, ok := dtc.mutation.UserID(); ok {
		if err := devicetoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.user_id": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DeviceToken.tenant_id"`)}
	}
	if v, ok := dtc.mutation.TenantID(); ok {
		if err := devicetoken.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.tenant_id": %w`, err)}
		}
	}
	if _, ok := dtc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceToken.created_at"`)}
	}
	return nil
}

func (dtc *DeviceTokenCreate) sqlSave(ctx context.Context) (*DeviceToken, error) {
	if err := dtc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dtc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DeviceToken.ID type: %T", _spec.ID.Value)
		}
	}
	dtc.mutation.id = &_node.ID
	dtc.mutation.done = true
	return _node, nil
}

func (dtc *DeviceTokenCreate) createSpec() (*DeviceToken, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceToken{config: dtc.config}
		_spec = sqlgraph.NewCreateSpec(devicetoken.Table, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeString))
	)
	_spec.Schema = dtc.schemaConfig.DeviceToken
	if id, ok := dtc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := dtc.mutation.TokenHash(); ok {
		_spec.SetField(devicetoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := dtc.mutation.UserID(); ok {
		_spec.SetField(devicetoken.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := dtc.mutation.TenantID(); ok {
		_spec.SetField(devicetoken.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := dtc.mutation.BranchID(); ok {
		_spec.SetField(devicetoken.FieldBranchID, field.TypeString, value)
		_node.BranchID = value
	}
	if value, ok := dtc.mutation.DeviceName(); ok {
		_spec.SetField(devicetoken.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := dtc.mutation.CreatedAt(); ok {
		_spec.SetField(devicetoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dtc.mutation.LastUsedAt(); ok {
		_spec.SetField(devicetoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := dtc.mutation.RevokedAt(); ok {
		_spec.SetField(devicetoken.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// DeviceTokenCreateBulk is the builder for creating many DeviceToken entities in bulk.
type DeviceTokenCreateBulk struct {
	config
	err      error
	builders []*DeviceTokenCreate
}

// Save creates the DeviceToken entities in the database.
func (dtcb *DeviceTokenCreateBulk) Save(ctx context.Context) ([]*DeviceToken, error) {
	if dtcb.err != nil {
		return nil, dtcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dtcb.builders))
	nodes := make([]*DeviceToken, len(dtcb.builders))
	mutators := make([]Mutator, len(dtcb.builders))
	for i := range dtcb.builders {
		func(i int, root context.Context) {
			builder := dtcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dtcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dtcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dtcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dtcb *DeviceTokenCreateBulk) SaveX(ctx context.Context) []*DeviceToken {
	v, err := dtcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dtcb *DeviceTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := dtcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtcb *DeviceTokenCreateBulk) ExecX(ctx context.Context) {
	if err := dtcb.Exec(ctx); err != nil {
		panic(err)
	}
}
