// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/devicetoken"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
)

// DeviceTokenUpdate is the builder for updating DeviceToken entities.
type DeviceTokenUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceTokenMutation
}

// Where appends a list predicates to the DeviceTokenUpdate builder.
func (dtu *DeviceTokenUpdate) Where(ps ...predicate.DeviceToken) *DeviceTokenUpdate {
	dtu.mutation.Where(ps...)
	return dtu
}

// SetTokenHash sets the "token_hash" field.
func (dtu *DeviceTokenUpdate) SetTokenHash(s string) *DeviceTokenUpdate {
	dtu.mutation.SetTokenHash(s)
	return dtu
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableTokenHash(s *string) *DeviceTokenUpdate {
	if s != nil {
		dtu.SetTokenHash(*s)
	}
	return dtu
}

// SetUserID sets the "user_id" field.
func (dtu *DeviceTokenUpdate) SetUserID(s string) *DeviceTokenUpdate {
	dtu.mutation.SetUserID(s)
	return dtu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableUserID(s *string) *DeviceTokenUpdate {
	if s != nil {
		dtu.SetUserID(*s)
	}
	return dtu
}

// SetTenantID sets the "tenant_id" field.
func (dtu *DeviceTokenUpdate) SetTenantID(s string) *DeviceTokenUpdate {
	dtu.mutation.SetTenantID(s)
	return dtu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableTenantID(s *string) *DeviceTokenUpdate {
	if s != nil {
		dtu.SetTenantID(*s)
	}
	return dtu
}

// SetBranchID sets the "branch_id" field.
func (dtu *DeviceTokenUpdate) SetBranchID(s string) *DeviceTokenUpdate {
	dtu.mutation.SetBranchID(s)
	return dtu
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableBranchID(s *string) *DeviceTokenUpdate {
	if s != nil {
		dtu.SetBranchID(*s)
	}
	return dtu
}

// ClearBranchID clears the value of the "branch_id" field.
func (dtu *DeviceTokenUpdate) ClearBranchID() *DeviceTokenUpdate {
	dtu.mutation.ClearBranchID()
	return dtu
}

// SetDeviceName sets the "device_name" field.
func (dtu *DeviceTokenUpdate) SetDeviceName(s string) *DeviceTokenUpdate {
	dtu.mutation.SetDeviceName(s)
	return dtu
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableDeviceName(s *string) *DeviceTokenUpdate {
	if s != nil {
		dtu.SetDeviceName(*s)
	}
	return dtu
}

// ClearDeviceName clears the value of the "device_name" field.
func (dtu *DeviceTokenUpdate) ClearDeviceName() *DeviceTokenUpdate {
	dtu.mutation.ClearDeviceName()
	return dtu
}

// SetLastUsedAt sets the "last_used_at" field.
func (dtu *DeviceTokenUpdate) SetLastUsedAt(t time.Time) *DeviceTokenUpdate {
	dtu.mutation.SetLastUsedAt(t)
	return dtu
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableLastUsedAt(t *time.Time) *DeviceTokenUpdate {
	if t != nil {
		dtu.SetLastUsedAt(*t)
	}
	return dtu
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (dtu *DeviceTokenUpdate) ClearLastUsedAt() *DeviceTokenUpdate {
	dtu.mutation.ClearLastUsedAt()
	return dtu
}

// SetRevokedAt sets the "revoked_at" field.
func (dtu *DeviceTokenUpdate) SetRevokedAt(t time.Time) *DeviceTokenUpdate {
	dtu.mutation.SetRevokedAt(t)
	return dtu
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (dtu *DeviceTokenUpdate) SetNillableRevokedAt(t *time.Time) *DeviceTokenUpdate {
	if t != nil {
		dtu.SetRevokedAt(*t)
	}
	return dtu
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (dtu *DeviceTokenUpdate) ClearRevokedAt() *DeviceTokenUpdate {
	dtu.mutation.ClearRevokedAt()
	return dtu
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (dtu *DeviceTokenUpdate) Mutation() *DeviceTokenMutation {
	return dtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dtu *DeviceTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, dtu.sqlSave, dtu.mutation, dtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dtu *DeviceTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := dtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dtu *DeviceTokenUpdate) Exec(ctx context.Context) error {
	_, err := dtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtu *DeviceTokenUpdate) ExecX(ctx context.Context) {
	if err := dtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dtu *DeviceTokenUpdate) check() error {
	if v, ok := dtu.mutation.TokenHash(); ok {
		if err := devicetoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.token_hash": %w`, err)}
		}
	}
	if v, ok := dtu.mutation.UserID(); ok {
		if err := devicetoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.user_id": %w`, err)}
		}
	}
	if v, ok := dtu.mutation.TenantID(); ok {
		if err := devicetoken.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (dtu *DeviceTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicetoken.Table, devicetoken.Columns, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeString))
	if ps := dtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dtu.mutation.TokenHash(); ok {
		_spec.SetField(devicetoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := dtu.mutation.UserID(); ok {
		_spec.SetField(devicetoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := dtu.mutation.TenantID(); ok {
		_spec.SetField(devicetoken.FieldTenantID, field.TypeString, value)
	}
	if value, ok := dtu.mutation.BranchID(); ok {
		_spec.SetField(devicetoken.FieldBranchID, field.TypeString, value)
	}
	if dtu.mutation.BranchIDCleared() {
		_spec.ClearField(devicetoken.FieldBranchID, field.TypeString)
	}
	if value, ok := dtu.mutation.DeviceName(); ok {
		_spec.SetField(devicetoken.FieldDeviceName, field.TypeString, value)
	}
	if dtu.mutation.DeviceNameCleared() {
		_spec.ClearField(devicetoken.FieldDeviceName, field.TypeString)
	}
	if value, ok := dtu.mutation.LastUsedAt(); ok {
		_spec.SetField(devicetoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if dtu.mutation.LastUsedAtCleared() {
		_spec.ClearField(devicetoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := dtu.mutation.RevokedAt(); ok {
		_spec.SetField(devicetoken.FieldRevokedAt, field.TypeTime, value)
	}
	if dtu.mutation.RevokedAtCleared() {
		_spec.ClearField(devicetoken.FieldRevokedAt, field.TypeTime)
	}
	_spec.Node.Schema = dtu.schemaConfig.DeviceToken
	ctx = internal.NewSchemaConfigContext(ctx, dtu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, dtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dtu.mutation.done = true
	return n, nil
}

// DeviceTokenUpdateOne is the builder for updating a single DeviceToken entity.
type DeviceTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (dtuo *DeviceTokenUpdateOne) SetTokenHash(s string) *DeviceTokenUpdateOne {
	dtuo.mutation.SetTokenHash(s)
	return dtuo
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableTokenHash(s *string) *DeviceTokenUpdateOne {
	if s != nil {
		dtuo.SetTokenHash(*s)
	}
	return dtuo
}

// SetUserID sets the "user_id" field.
func (dtuo *DeviceTokenUpdateOne) SetUserID(s string) *DeviceTokenUpdateOne {
	dtuo.mutation.SetUserID(s)
	return dtuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableUserID(s *string) *DeviceTokenUpdateOne {
	if s != nil {
		dtuo.SetUserID(*s)
	}
	return dtuo
}

// SetTenantID sets the "tenant_id" field.
func (dtuo *DeviceTokenUpdateOne) SetTenantID(s string) *DeviceTokenUpdateOne {
	dtuo.mutation.SetTenantID(s)
	return dtuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableTenantID(s *string) *DeviceTokenUpdateOne {
	if s != nil {
		dtuo.SetTenantID(*s)
	}
	return dtuo
}

// SetBranchID sets the "branch_id" field.
func (dtuo *DeviceTokenUpdateOne) SetBranchID(s string) *DeviceTokenUpdateOne {
	dtuo.mutation.SetBranchID(s)
	return dtuo
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableBranchID(s *string) *DeviceTokenUpdateOne {
	if s != nil {
		dtuo.SetBranchID(*s)
	}
	return dtuo
}

// ClearBranchID clears the value of the "branch_id" field.
func (dtuo *DeviceTokenUpdateOne) ClearBranchID() *DeviceTokenUpdateOne {
	dtuo.mutation.ClearBranchID()
	return dtuo
}

// SetDeviceName sets the "device_name" field.
func (dtuo *DeviceTokenUpdateOne) SetDeviceName(s string) *DeviceTokenUpdateOne {
	dtuo.mutation.SetDeviceName(s)
	return dtuo
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableDeviceName(s *string) *DeviceTokenUpdateOne {
	if s != nil {
		dtuo.SetDeviceName(*s)
	}
	return dtuo
}

// ClearDeviceName clears the value of the "device_name" field.
func (dtuo *DeviceTokenUpdateOne) ClearDeviceName() *DeviceTokenUpdateOne {
	dtuo.mutation.ClearDeviceName()
	return dtuo
}

// SetLastUsedAt sets the "last_used_at" field.
func (dtuo *DeviceTokenUpdateOne) SetLastUsedAt(t time.Time) *DeviceTokenUpdateOne {
	dtuo.mutation.SetLastUsedAt(t)
	return dtuo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableLastUsedAt(t *time.Time) *DeviceTokenUpdateOne {
	if t != nil {
		dtuo.SetLastUsedAt(*t)
	}
	return dtuo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (dtuo *DeviceTokenUpdateOne) ClearLastUsedAt() *DeviceTokenUpdateOne {
	dtuo.mutation.ClearLastUsedAt()
	return dtuo
}

// SetRevokedAt sets the "revoked_at" field.
func (dtuo *DeviceTokenUpdateOne) SetRevokedAt(t time.Time) *DeviceTokenUpdateOne {
	dtuo.mutation.SetRevokedAt(t)
	return dtuo
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (dtuo *DeviceTokenUpdateOne) SetNillableRevokedAt(t *time.Time) *DeviceTokenUpdateOne {
	if t != nil {
		dtuo.SetRevokedAt(*t)
	}
	return dtuo
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (dtuo *DeviceTokenUpdateOne) ClearRevokedAt() *DeviceTokenUpdateOne {
	dtuo.mutation.ClearRevokedAt()
	return dtuo
}

// Mutation returns the DeviceTokenMutation object of the builder.
func (dtuo *DeviceTokenUpdateOne) Mutation() *DeviceTokenMutation {
	return dtuo.mutation
}

// Where appends a list predicates to the DeviceTokenUpdate builder.
func (dtuo *DeviceTokenUpdateOne) Where(ps ...predicate.DeviceToken) *DeviceTokenUpdateOne {
	dtuo.mutation.Where(ps...)
	return dtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (dtuo *DeviceTokenUpdateOne) Select(field string, fields ...string) *DeviceTokenUpdateOne {
	dtuo.fields = append([]string{field}, fields...)
	return dtuo
}

// Save executes the query and returns the updated DeviceToken entity.
func (dtuo *DeviceTokenUpdateOne) Save(ctx context.Context) (*DeviceToken, error) {
	return withHooks(ctx, dtuo.sqlSave, dtuo.mutation, dtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dtuo *DeviceTokenUpdateOne) SaveX(ctx context.Context) *DeviceToken {
	node, err := dtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (dtuo *DeviceTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := dtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dtuo *DeviceTokenUpdateOne) ExecX(ctx context.Context) {
	if err := dtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dtuo *DeviceTokenUpdateOne) check() error {
	if v, ok := dtuo.mutation.TokenHash(); ok {
		if err := devicetoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.token_hash": %w`, err)}
		}
	}
	if v, ok := dtuo.mutation.UserID(); ok {
		if err := devicetoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.user_id": %w`, err)}
		}
	}
	if v, ok := dtuo.mutation.TenantID(); ok {
		if err := devicetoken.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "DeviceToken.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (dtuo *DeviceTokenUpdateOne) sqlSave(ctx context.Context) (_node *DeviceToken, err error) {
	if err := dtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicetoken.Table, devicetoken.Columns, sqlgraph.NewFieldSpec(devicetoken.FieldID, field.TypeString))
	id, ok := dtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := dtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicetoken.FieldID)
		for _, f := range fields {
			if !devicetoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != devicetoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := dtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dtuo.mutation.TokenHash(); ok {
		_spec.SetField(devicetoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := dtuo.mutation.UserID(); ok {
		_spec.SetField(devicetoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := dtuo.mutation.TenantID(); ok {
		_spec.SetField(devicetoken.FieldTenantID, field.TypeString, value)
	}
	if value, ok := dtuo.mutation.BranchID(); ok {
		_spec.SetField(devicetoken.FieldBranchID, field.TypeString, value)
	}
	if dtuo.mutation.BranchIDCleared() {
		_spec.ClearField(devicetoken.FieldBranchID, field.TypeString)
	}
	if value, ok := dtuo.mutation.DeviceName(); ok {
		_spec.SetField(devicetoken.FieldDeviceName, field.TypeString, value)
	}
	if dtuo.mutation.DeviceNameCleared() {
		_spec.ClearField(devicetoken.FieldDeviceName, field.TypeString)
	}
	if value, ok := dtuo.mutation.LastUsedAt(); ok {
		_spec.SetField(devicetoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if dtuo.mutation.LastUsedAtCleared() {
		_spec.ClearField(devicetoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := dtuo.mutation.RevokedAt(); ok {
		_spec.SetField(devicetoken.FieldRevokedAt, field.TypeTime, value)
	}
	if dtuo.mutation.RevokedAtCleared() {
		_spec.ClearField(devicetoken.FieldRevokedAt, field.TypeTime)
	}
	_spec.Node.Schema = dtuo.schemaConfig.DeviceToken
	ctx = internal.NewSchemaConfigContext(ctx, dtuo.schemaConfig)
	_node = &DeviceToken{config: dtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, dtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicetoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	dtuo.mutation.done = true
	return _node, nil
}
