// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
)

// PluginInstall is the model entity for the PluginInstall schema.
type PluginInstall struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// PluginName holds the value of the "plugin_name" field.
	PluginName string `json:"plugin_name,omitempty"`
	// InstalledAt holds the value of the "installed_at" field.
	InstalledAt time.Time `json:"installed_at,omitempty"`
	// Permissions holds the value of the "permissions" field.
	Permissions []string `json:"permissions,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginInstallQuery when eager-loading is set.
	Edges        PluginInstallEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PluginInstallEdges holds the relations/edges for other nodes in the graph.
type PluginInstallEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginInstallEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginInstall) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plugininstall.FieldPermissions:
			values[i] = new([]byte)
		case plugininstall.FieldID, plugininstall.FieldTenantID, plugininstall.FieldPluginName:
			values[i] = new(sql.NullString)
		case plugininstall.FieldInstalledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginInstall fields.
func (pi *PluginInstall) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plugininstall.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pi.ID = value.String
			}
		case plugininstall.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				pi.TenantID = value.String
			}
		case plugininstall.FieldPluginName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_name", values[i])
			} else if value.Valid {
				pi.PluginName = value.String
			}
		case plugininstall.FieldInstalledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field installed_at", values[i])
			} else if value.Valid {
				pi.InstalledAt = value.Time
			}
		case plugininstall.FieldPermissions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field permissions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &pi.Permissions); err != nil {
					return fmt.Errorf("unmarshal field permissions: %w", err)
				}
			}
		default:
			pi.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginInstall.
// This includes values selected through modifiers, order, etc.
func (pi *PluginInstall) Value(name string) (ent.Value, error) {
	return pi.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the PluginInstall entity.
func (pi *PluginInstall) QueryTenant() *TenantQuery {
	return NewPluginInstallClient(pi.config).QueryTenant(pi)
}

// Update returns a builder for updating this PluginInstall.
// Note that you need to call PluginInstall.Unwrap() before calling this method if this PluginInstall
// was returned from a transaction, and the transaction was committed or rolled back.
func (pi *PluginInstall) Update() *PluginInstallUpdateOne {
	return NewPluginInstallClient(pi.config).UpdateOne(pi)
}

// Unwrap unwraps the PluginInstall entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pi *PluginInstall) Unwrap() *PluginInstall {
	_tx, ok := pi.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginInstall is not a transactional entity")
	}
	pi.config.driver = _tx.drv
	return pi
}

// String implements the fmt.Stringer.
func (pi *PluginInstall) String() string {
	var builder strings.Builder
	builder.WriteString("PluginInstall(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pi.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(pi.TenantID)
	builder.WriteString(", ")
	builder.WriteString("plugin_name=")
	builder.WriteString(pi.PluginName)
	builder.WriteString(", ")
	builder.WriteString("installed_at=")
	builder.WriteString(pi.InstalledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("permissions=")
	builder.WriteString(fmt.Sprintf("%v", pi.Permissions))
	builder.WriteByte(')')
	return builder.String()
}

// PluginInstalls is a parsable slice of PluginInstall.
type PluginInstalls []*PluginInstall
