// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
)

// PluginInstallQuery is the builder for querying PluginInstall entities.
type PluginInstallQuery struct {
	config
	ctx        *QueryContext
	order      []plugininstall.OrderOption
	inters     []Interceptor
	predicates []predicate.PluginInstall
	withTenant *TenantQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PluginInstallQuery builder.
func (piq *PluginInstallQuery) Where(ps ...predicate.PluginInstall) *PluginInstallQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *PluginInstallQuery) Limit(limit int) *PluginInstallQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *PluginInstallQuery) Offset(offset int) *PluginInstallQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *PluginInstallQuery) Unique(unique bool) *PluginInstallQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *PluginInstallQuery) Order(o ...plugininstall.OrderOption) *PluginInstallQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QueryTenant chains the current query on the "tenant" edge.
func (piq *PluginInstallQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plugininstall.Table, plugininstall.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, plugininstall.TenantTable, plugininstall.TenantColumn),
		)
		schemaConfig := piq.schemaConfig
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.PluginInstall
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PluginInstall entity from the query.
// Returns a *NotFoundError when no PluginInstall was found.
func (piq *PluginInstallQuery) First(ctx context.Context) (*PluginInstall, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{plugininstall.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *PluginInstallQuery) FirstX(ctx context.Context) *PluginInstall {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PluginInstall ID from the query.
// Returns a *NotFoundError when no PluginInstall ID was found.
func (piq *PluginInstallQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{plugininstall.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *PluginInstallQuery) FirstIDX(ctx context.Context) string {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PluginInstall entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PluginInstall entity is found.
// Returns a *NotFoundError when no PluginInstall entities are found.
func (piq *PluginInstallQuery) Only(ctx context.Context) (*PluginInstall, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{plugininstall.Label}
	default:
		return nil, &NotSingularError{plugininstall.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *PluginInstallQuery) OnlyX(ctx context.Context) *PluginInstall {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PluginInstall ID in the query.
// Returns a *NotSingularError when more than one PluginInstall ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *PluginInstallQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{plugininstall.Label}
	default:
		err = &NotSingularError{plugininstall.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *PluginInstallQuery) OnlyIDX(ctx context.Context) string {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PluginInstalls.
func (piq *PluginInstallQuery) All(ctx context.Context) ([]*PluginInstall, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryAll)
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PluginInstall, *PluginInstallQuery]()
	return withInterceptors[[]*PluginInstall](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *PluginInstallQuery) AllX(ctx context.Context) []*PluginInstall {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PluginInstall IDs.
func (piq *PluginInstallQuery) IDs(ctx context.Context) (ids []string, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryIDs)
	if err = piq.Select(plugininstall.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *PluginInstallQuery) IDsX(ctx context.Context) []string {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *PluginInstallQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryCount)
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*PluginInstallQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *PluginInstallQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *PluginInstallQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, ent.OpQueryExist)
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *PluginInstallQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PluginInstallQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *PluginInstallQuery) Clone() *PluginInstallQuery {
	if piq == nil {
		return nil
	}
	return &PluginInstallQuery{
		config:     piq.config,
		ctx:        piq.ctx.Clone(),
		order:      append([]plugininstall.OrderOption{}, piq.order...),
		inters:     append([]Interceptor{}, piq.inters...),
		predicates: append([]predicate.PluginInstall{}, piq.predicates...),
		withTenant: piq.withTenant.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *PluginInstallQuery) WithTenant(opts ...func(*TenantQuery)) *PluginInstallQuery {
	query := (&TenantClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withTenant = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PluginInstall.Query().
//		GroupBy(plugininstall.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *PluginInstallQuery) GroupBy(field string, fields ...string) *PluginInstallGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PluginInstallGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = plugininstall.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.PluginInstall.Query().
//		Select(plugininstall.FieldTenantID).
//		Scan(ctx, &v)
func (piq *PluginInstallQuery) Select(fields ...string) *PluginInstallSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &PluginInstallSelect{PluginInstallQuery: piq}
	sbuild.label = plugininstall.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PluginInstallSelect configured with the given aggregations.
func (piq *PluginInstallQuery) Aggregate(fns ...AggregateFunc) *PluginInstallSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *PluginInstallQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !plugininstall.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *PluginInstallQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PluginInstall, error) {
	var (
		nodes       = []*PluginInstall{}
		_spec       = piq.querySpec()
		loadedTypes = [1]bool{
			piq.withTenant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PluginInstall).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PluginInstall{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = piq.schemaConfig.PluginInstall
	ctx = internal.NewSchemaConfigContext(ctx, piq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withTenant; query != nil {
		if err := piq.loadTenant(ctx, query, nodes, nil,
			func(n *PluginInstall, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *PluginInstallQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*PluginInstall, init func(*PluginInstall), assign func(*PluginInstall, *Tenant)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PluginInstall)
	for i := range nodes {
		fk := nodes[i].TenantID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *PluginInstallQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	_spec.Node.Schema = piq.schemaConfig.PluginInstall
	ctx = internal.NewSchemaConfigContext(ctx, piq.schemaConfig)
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *PluginInstallQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(plugininstall.Table, plugininstall.Columns, sqlgraph.NewFieldSpec(plugininstall.FieldID, field.TypeString))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugininstall.FieldID)
		for i := range fields {
			if fields[i] != plugininstall.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if piq.withTenant != nil {
			_spec.Node.AddColumnOnce(plugininstall.FieldTenantID)
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *PluginInstallQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(plugininstall.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = plugininstall.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(piq.schemaConfig.PluginInstall)
	ctx = internal.NewSchemaConfigContext(ctx, piq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PluginInstallGroupBy is the group-by builder for PluginInstall entities.
type PluginInstallGroupBy struct {
	selector
	build *PluginInstallQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *PluginInstallGroupBy) Aggregate(fns ...AggregateFunc) *PluginInstallGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *PluginInstallGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, ent.OpQueryGroupBy)
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PluginInstallQuery, *PluginInstallGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *PluginInstallGroupBy) sqlScan(ctx context.Context, root *PluginInstallQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PluginInstallSelect is the builder for selecting fields of PluginInstall entities.
type PluginInstallSelect struct {
	*PluginInstallQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *PluginInstallSelect) Aggregate(fns ...AggregateFunc) *PluginInstallSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *PluginInstallSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, ent.OpQuerySelect)
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PluginInstallQuery, *PluginInstallSelect](ctx, pis.PluginInstallQuery, pis, pis.inters, v)
}

func (pis *PluginInstallSelect) sqlScan(ctx context.Context, root *PluginInstallQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
