// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
)

// PluginInstallCreate is the builder for creating a PluginInstall entity.
type PluginInstallCreate struct {
	config
	mutation *PluginInstallMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (pic *PluginInstallCreate) SetTenantID(s string) *PluginInstallCreate {
	pic.mutation.SetTenantID(s)
	return pic
}

// SetPluginName sets the "plugin_name" field.
func (pic *PluginInstallCreate) SetPluginName(s string) *PluginInstallCreate {
	pic.mutation.SetPluginName(s)
	return pic
}

// SetInstalledAt sets the "installed_at" field.
func (pic *PluginInstallCreate) SetInstalledAt(t time.Time) *PluginInstallCreate {
	pic.mutation.SetInstalledAt(t)
	return pic
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (pic *PluginInstallCreate) SetNillableInstalledAt(t *time.Time) *PluginInstallCreate {
	if t != nil {
		pic.SetInstalledAt(*t)
	}
	return pic
}

// SetPermissions sets the "permissions" field.
func (pic *PluginInstallCreate) SetPermissions(s []string) *PluginInstallCreate {
	pic.mutation.SetPermissions(s)
	return pic
}

// SetID sets the "id" field.
func (pic *PluginInstallCreate) SetID(s string) *PluginInstallCreate {
	pic.mutation.SetID(s)
	return pic
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (pic *PluginInstallCreate) SetTenant(t *Tenant) *PluginInstallCreate {
	return pic.SetTenantID(t.ID)
}

// Mutation returns the PluginInstallMutation object of the builder.
func (pic *PluginInstallCreate) Mutation() *PluginInstallMutation {
	return pic.mutation
}

// Save creates the PluginInstall in the database.
func (pic *PluginInstallCreate) Save(ctx context.Context) (*PluginInstall, error) {
	pic.defaults()
	return withHooks(ctx, pic.sqlSave, pic.mutation, pic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pic *PluginInstallCreate) SaveX(ctx context.Context) *PluginInstall {
	v, err := pic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pic *PluginInstallCreate) Exec(ctx context.Context) error {
	_, err := pic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pic *PluginInstallCreate) ExecX(ctx context.Context) {
	if err := pic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pic *PluginInstallCreate) defaults() {
	if _, ok := pic.mutation.InstalledAt(); !ok {
		v := plugininstall.DefaultInstalledAt()
		pic.mutation.SetInstalledAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pic *PluginInstallCreate) check() error {
	if _, ok := pic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PluginInstall.tenant_id"`)}
	}
	if _, ok := pic.mutation.PluginName(); !ok {
		return &ValidationError{Name: "plugin_name", err: errors.New(`ent: missing required field "PluginInstall.plugin_name"`)}
	}
	if _, ok := pic.mutation.InstalledAt(); !ok {
		return &ValidationError{Name: "installed_at", err: errors.New(`ent: missing required field "PluginInstall.installed_at"`)}
	}
	if len(pic.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "PluginInstall.tenant"`)}
	}
	return nil
}

func (pic *PluginInstallCreate) sqlSave(ctx context.Context) (*PluginInstall, error) {
	if err := pic.check(); err != nil {
		return nil, err
	}
	_node, _spec := pic.createSpec()
	if err := sqlgraph.CreateNode(ctx, pic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PluginInstall.ID type: %T", _spec.ID.Value)
		}
	}
	pic.mutation.id = &_node.ID
	pic.mutation.done = true
	return _node, nil
}

func (pic *PluginInstallCreate) createSpec() (*PluginInstall, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginInstall{config: pic.config}
		_spec = sqlgraph.NewCreateSpec(plugininstall.Table, sqlgraph.NewFieldSpec(plugininstall.FieldID, field.TypeString))
	)
	_spec.Schema = pic.schemaConfig.PluginInstall
	if id, ok := pic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := pic.mutation.PluginName(); ok {
		_spec.SetField(plugininstall.FieldPluginName, field.TypeString, value)
		_node.PluginName = value
	}
	if value, ok := pic.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstall.FieldInstalledAt, field.TypeTime, value)
		_node.InstalledAt = value
	}
	if value, ok := pic.mutation.Permissions(); ok {
		_spec.SetField(plugininstall.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if nodes := pic.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plugininstall.TenantTable,
			Columns: []string{plugininstall.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = pic.schemaConfig.PluginInstall
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginInstallCreateBulk is the builder for creating many PluginInstall entities in bulk.
type PluginInstallCreateBulk struct {
	config
	err      error
	builders []*PluginInstallCreate
}

// Save creates the PluginInstall entities in the database.
func (picb *PluginInstallCreateBulk) Save(ctx context.Context) ([]*PluginInstall, error) {
	if picb.err != nil {
		return nil, picb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(picb.builders))
	nodes := make([]*PluginInstall, len(picb.builders))
	mutators := make([]Mutator, len(picb.builders))
	for i := range picb.builders {
		func(i int, root context.Context) {
			builder := picb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginInstallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, picb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, picb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, picb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (picb *PluginInstallCreateBulk) SaveX(ctx context.Context) []*PluginInstall {
	v, err := picb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (picb *PluginInstallCreateBulk) Exec(ctx context.Context) error {
	_, err := picb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (picb *PluginInstallCreateBulk) ExecX(ctx context.Context) {
	if err := picb.Exec(ctx); err != nil {
		panic(err)
	}
}
