// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/pluginmigrationhistory"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
)

// PluginMigrationHistoryUpdate is the builder for updating PluginMigrationHistory entities.
type PluginMigrationHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *PluginMigrationHistoryMutation
}

// Where appends a list predicates to the PluginMigrationHistoryUpdate builder.
func (pmhu *PluginMigrationHistoryUpdate) Where(ps ...predicate.PluginMigrationHistory) *PluginMigrationHistoryUpdate {
	pmhu.mutation.Where(ps...)
	return pmhu
}

// SetTenantID sets the "tenant_id" field.
func (pmhu *PluginMigrationHistoryUpdate) SetTenantID(s string) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetTenantID(s)
	return pmhu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillableTenantID(s *string) *PluginMigrationHistoryUpdate {
	if s != nil {
		pmhu.SetTenantID(*s)
	}
	return pmhu
}

// SetPluginName sets the "plugin_name" field.
func (pmhu *PluginMigrationHistoryUpdate) SetPluginName(s string) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetPluginName(s)
	return pmhu
}

// SetNillablePluginName sets the "plugin_name" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillablePluginName(s *string) *PluginMigrationHistoryUpdate {
	if s != nil {
		pmhu.SetPluginName(*s)
	}
	return pmhu
}

// SetVersion sets the "version" field.
func (pmhu *PluginMigrationHistoryUpdate) SetVersion(s string) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetVersion(s)
	return pmhu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillableVersion(s *string) *PluginMigrationHistoryUpdate {
	if s != nil {
		pmhu.SetVersion(*s)
	}
	return pmhu
}

// SetName sets the "name" field.
func (pmhu *PluginMigrationHistoryUpdate) SetName(s string) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetName(s)
	return pmhu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillableName(s *string) *PluginMigrationHistoryUpdate {
	if s != nil {
		pmhu.SetName(*s)
	}
	return pmhu
}

// SetStatus sets the "status" field.
func (pmhu *PluginMigrationHistoryUpdate) SetStatus(s string) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetStatus(s)
	return pmhu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillableStatus(s *string) *PluginMigrationHistoryUpdate {
	if s != nil {
		pmhu.SetStatus(*s)
	}
	return pmhu
}

// SetAppliedAt sets the "applied_at" field.
func (pmhu *PluginMigrationHistoryUpdate) SetAppliedAt(t time.Time) *PluginMigrationHistoryUpdate {
	pmhu.mutation.SetAppliedAt(t)
	return pmhu
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (pmhu *PluginMigrationHistoryUpdate) SetNillableAppliedAt(t *time.Time) *PluginMigrationHistoryUpdate {
	if t != nil {
		pmhu.SetAppliedAt(*t)
	}
	return pmhu
}

// Mutation returns the PluginMigrationHistoryMutation object of the builder.
func (pmhu *PluginMigrationHistoryUpdate) Mutation() *PluginMigrationHistoryMutation {
	return pmhu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pmhu *PluginMigrationHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pmhu.sqlSave, pmhu.mutation, pmhu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pmhu *PluginMigrationHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := pmhu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pmhu *PluginMigrationHistoryUpdate) Exec(ctx context.Context) error {
	_, err := pmhu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmhu *PluginMigrationHistoryUpdate) ExecX(ctx context.Context) {
	if err := pmhu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pmhu *PluginMigrationHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pluginmigrationhistory.Table, pluginmigrationhistory.Columns, sqlgraph.NewFieldSpec(pluginmigrationhistory.FieldID, field.TypeString))
	if ps := pmhu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pmhu.mutation.TenantID(); ok {
		_spec.SetField(pluginmigrationhistory.FieldTenantID, field.TypeString, value)
	}
	if value, ok := pmhu.mutation.PluginName(); ok {
		_spec.SetField(pluginmigrationhistory.FieldPluginName, field.TypeString, value)
	}
	if value, ok := pmhu.mutation.Version(); ok {
		_spec.SetField(pluginmigrationhistory.FieldVersion, field.TypeString, value)
	}
	if value, ok := pmhu.mutation.Name(); ok {
		_spec.SetField(pluginmigrationhistory.FieldName, field.TypeString, value)
	}
	if value, ok := pmhu.mutation.Status(); ok {
		_spec.SetField(pluginmigrationhistory.FieldStatus, field.TypeString, value)
	}
	if value, ok := pmhu.mutation.AppliedAt(); ok {
		_spec.SetField(pluginmigrationhistory.FieldAppliedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = pmhu.schemaConfig.PluginMigrationHistory
	ctx = internal.NewSchemaConfigContext(ctx, pmhu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, pmhu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginmigrationhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pmhu.mutation.done = true
	return n, nil
}

// PluginMigrationHistoryUpdateOne is the builder for updating a single PluginMigrationHistory entity.
type PluginMigrationHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginMigrationHistoryMutation
}

// SetTenantID sets the "tenant_id" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetTenantID(s string) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetTenantID(s)
	return pmhuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillableTenantID(s *string) *PluginMigrationHistoryUpdateOne {
	if s != nil {
		pmhuo.SetTenantID(*s)
	}
	return pmhuo
}

// SetPluginName sets the "plugin_name" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetPluginName(s string) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetPluginName(s)
	return pmhuo
}

// SetNillablePluginName sets the "plugin_name" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillablePluginName(s *string) *PluginMigrationHistoryUpdateOne {
	if s != nil {
		pmhuo.SetPluginName(*s)
	}
	return pmhuo
}

// SetVersion sets the "version" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetVersion(s string) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetVersion(s)
	return pmhuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillableVersion(s *string) *PluginMigrationHistoryUpdateOne {
	if s != nil {
		pmhuo.SetVersion(*s)
	}
	return pmhuo
}

// SetName sets the "name" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetName(s string) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetName(s)
	return pmhuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillableName(s *string) *PluginMigrationHistoryUpdateOne {
	if s != nil {
		pmhuo.SetName(*s)
	}
	return pmhuo
}

// SetStatus sets the "status" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetStatus(s string) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetStatus(s)
	return pmhuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillableStatus(s *string) *PluginMigrationHistoryUpdateOne {
	if s != nil {
		pmhuo.SetStatus(*s)
	}
	return pmhuo
}

// SetAppliedAt sets the "applied_at" field.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetAppliedAt(t time.Time) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.SetAppliedAt(t)
	return pmhuo
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (pmhuo *PluginMigrationHistoryUpdateOne) SetNillableAppliedAt(t *time.Time) *PluginMigrationHistoryUpdateOne {
	if t != nil {
		pmhuo.SetAppliedAt(*t)
	}
	return pmhuo
}

// Mutation returns the PluginMigrationHistoryMutation object of the builder.
func (pmhuo *PluginMigrationHistoryUpdateOne) Mutation() *PluginMigrationHistoryMutation {
	return pmhuo.mutation
}

// Where appends a list predicates to the PluginMigrationHistoryUpdate builder.
func (pmhuo *PluginMigrationHistoryUpdateOne) Where(ps ...predicate.PluginMigrationHistory) *PluginMigrationHistoryUpdateOne {
	pmhuo.mutation.Where(ps...)
	return pmhuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pmhuo *PluginMigrationHistoryUpdateOne) Select(field string, fields ...string) *PluginMigrationHistoryUpdateOne {
	pmhuo.fields = append([]string{field}, fields...)
	return pmhuo
}

// Save executes the query and returns the updated PluginMigrationHistory entity.
func (pmhuo *PluginMigrationHistoryUpdateOne) Save(ctx context.Context) (*PluginMigrationHistory, error) {
	return withHooks(ctx, pmhuo.sqlSave, pmhuo.mutation, pmhuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pmhuo *PluginMigrationHistoryUpdateOne) SaveX(ctx context.Context) *PluginMigrationHistory {
	node, err := pmhuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pmhuo *PluginMigrationHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := pmhuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmhuo *PluginMigrationHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := pmhuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pmhuo *PluginMigrationHistoryUpdateOne) sqlSave(ctx context.Context) (_node *PluginMigrationHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(pluginmigrationhistory.Table, pluginmigrationhistory.Columns, sqlgraph.NewFieldSpec(pluginmigrationhistory.FieldID, field.TypeString))
	id, ok := pmhuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginMigrationHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pmhuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginmigrationhistory.FieldID)
		for _, f := range fields {
			if !pluginmigrationhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginmigrationhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pmhuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pmhuo.mutation.TenantID(); ok {
		_spec.SetField(pluginmigrationhistory.FieldTenantID, field.TypeString, value)
	}
	if value, ok := pmhuo.mutation.PluginName(); ok {
		_spec.SetField(pluginmigrationhistory.FieldPluginName, field.TypeString, value)
	}
	if value, ok := pmhuo.mutation.Version(); ok {
		_spec.SetField(pluginmigrationhistory.FieldVersion, field.TypeString, value)
	}
	if value, ok := pmhuo.mutation.Name(); ok {
		_spec.SetField(pluginmigrationhistory.FieldName, field.TypeString, value)
	}
	if value, ok := pmhuo.mutation.Status(); ok {
		_spec.SetField(pluginmigrationhistory.FieldStatus, field.TypeString, value)
	}
	if value, ok := pmhuo.mutation.AppliedAt(); ok {
		_spec.SetField(pluginmigrationhistory.FieldAppliedAt, field.TypeTime, value)
	}
	_spec.Node.Schema = pmhuo.schemaConfig.PluginMigrationHistory
	ctx = internal.NewSchemaConfigContext(ctx, pmhuo.schemaConfig)
	_node = &PluginMigrationHistory{config: pmhuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pmhuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginmigrationhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pmhuo.mutation.done = true
	return _node, nil
}
