// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
)

// PluginInstallUpdate is the builder for updating PluginInstall entities.
type PluginInstallUpdate struct {
	config
	hooks    []Hook
	mutation *PluginInstallMutation
}

// Where appends a list predicates to the PluginInstallUpdate builder.
func (piu *PluginInstallUpdate) Where(ps ...predicate.PluginInstall) *PluginInstallUpdate {
	piu.mutation.Where(ps...)
	return piu
}

// SetTenantID sets the "tenant_id" field.
func (piu *PluginInstallUpdate) SetTenantID(s string) *PluginInstallUpdate {
	piu.mutation.SetTenantID(s)
	return piu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (piu *PluginInstallUpdate) SetNillableTenantID(s *string) *PluginInstallUpdate {
	if s != nil {
		piu.SetTenantID(*s)
	}
	return piu
}

// SetPluginName sets the "plugin_name" field.
func (piu *PluginInstallUpdate) SetPluginName(s string) *PluginInstallUpdate {
	piu.mutation.SetPluginName(s)
	return piu
}

// SetNillablePluginName sets the "plugin_name" field if the given value is not nil.
func (piu *PluginInstallUpdate) SetNillablePluginName(s *string) *PluginInstallUpdate {
	if s != nil {
		piu.SetPluginName(*s)
	}
	return piu
}

// SetInstalledAt sets the "installed_at" field.
func (piu *PluginInstallUpdate) SetInstalledAt(t time.Time) *PluginInstallUpdate {
	piu.mutation.SetInstalledAt(t)
	return piu
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (piu *PluginInstallUpdate) SetNillableInstalledAt(t *time.Time) *PluginInstallUpdate {
	if t != nil {
		piu.SetInstalledAt(*t)
	}
	return piu
}

// SetPermissions sets the "permissions" field.
func (piu *PluginInstallUpdate) SetPermissions(s []string) *PluginInstallUpdate {
	piu.mutation.SetPermissions(s)
	return piu
}

// AppendPermissions appends s to the "permissions" field.
func (piu *PluginInstallUpdate) AppendPermissions(s []string) *PluginInstallUpdate {
	piu.mutation.AppendPermissions(s)
	return piu
}

// ClearPermissions clears the value of the "permissions" field.
func (piu *PluginInstallUpdate) ClearPermissions() *PluginInstallUpdate {
	piu.mutation.ClearPermissions()
	return piu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (piu *PluginInstallUpdate) SetTenant(t *Tenant) *PluginInstallUpdate {
	return piu.SetTenantID(t.ID)
}

// Mutation returns the PluginInstallMutation object of the builder.
func (piu *PluginInstallUpdate) Mutation() *PluginInstallMutation {
	return piu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (piu *PluginInstallUpdate) ClearTenant() *PluginInstallUpdate {
	piu.mutation.ClearTenant()
	return piu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (piu *PluginInstallUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, piu.sqlSave, piu.mutation, piu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (piu *PluginInstallUpdate) SaveX(ctx context.Context) int {
	affected, err := piu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (piu *PluginInstallUpdate) Exec(ctx context.Context) error {
	_, err := piu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piu *PluginInstallUpdate) ExecX(ctx context.Context) {
	if err := piu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (piu *PluginInstallUpdate) check() error {
	if piu.mutation.TenantCleared() && len(piu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginInstall.tenant"`)
	}
	return nil
}

func (piu *PluginInstallUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := piu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugininstall.Table, plugininstall.Columns, sqlgraph.NewFieldSpec(plugininstall.FieldID, field.TypeString))
	if ps := piu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piu.mutation.PluginName(); ok {
		_spec.SetField(plugininstall.FieldPluginName, field.TypeString, value)
	}
	if value, ok := piu.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstall.FieldInstalledAt, field.TypeTime, value)
	}
	if value, ok := piu.mutation.Permissions(); ok {
		_spec.SetField(plugininstall.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := piu.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstall.FieldPermissions, value)
		})
	}
	if piu.mutation.PermissionsCleared() {
		_spec.ClearField(plugininstall.FieldPermissions, field.TypeJSON)
	}
	if piu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plugininstall.TenantTable,
			Columns: []string{plugininstall.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = piu.schemaConfig.PluginInstall
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := piu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plugininstall.TenantTable,
			Columns: []string{plugininstall.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = piu.schemaConfig.PluginInstall
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = piu.schemaConfig.PluginInstall
	ctx = internal.NewSchemaConfigContext(ctx, piu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, piu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugininstall.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	piu.mutation.done = true
	return n, nil
}

// PluginInstallUpdateOne is the builder for updating a single PluginInstall entity.
type PluginInstallUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginInstallMutation
}

// SetTenantID sets the "tenant_id" field.
func (piuo *PluginInstallUpdateOne) SetTenantID(s string) *PluginInstallUpdateOne {
	piuo.mutation.SetTenantID(s)
	return piuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (piuo *PluginInstallUpdateOne) SetNillableTenantID(s *string) *PluginInstallUpdateOne {
	if s != nil {
		piuo.SetTenantID(*s)
	}
	return piuo
}

// SetPluginName sets the "plugin_name" field.
func (piuo *PluginInstallUpdateOne) SetPluginName(s string) *PluginInstallUpdateOne {
	piuo.mutation.SetPluginName(s)
	return piuo
}

// SetNillablePluginName sets the "plugin_name" field if the given value is not nil.
func (piuo *PluginInstallUpdateOne) SetNillablePluginName(s *string) *PluginInstallUpdateOne {
	if s != nil {
		piuo.SetPluginName(*s)
	}
	return piuo
}

// SetInstalledAt sets the "installed_at" field.
func (piuo *PluginInstallUpdateOne) SetInstalledAt(t time.Time) *PluginInstallUpdateOne {
	piuo.mutation.SetInstalledAt(t)
	return piuo
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (piuo *PluginInstallUpdateOne) SetNillableInstalledAt(t *time.Time) *PluginInstallUpdateOne {
	if t != nil {
		piuo.SetInstalledAt(*t)
	}
	return piuo
}

// SetPermissions sets the "permissions" field.
func (piuo *PluginInstallUpdateOne) SetPermissions(s []string) *PluginInstallUpdateOne {
	piuo.mutation.SetPermissions(s)
	return piuo
}

// AppendPermissions appends s to the "permissions" field.
func (piuo *PluginInstallUpdateOne) AppendPermissions(s []string) *PluginInstallUpdateOne {
	piuo.mutation.AppendPermissions(s)
	return piuo
}

// ClearPermissions clears the value of the "permissions" field.
func (piuo *PluginInstallUpdateOne) ClearPermissions() *PluginInstallUpdateOne {
	piuo.mutation.ClearPermissions()
	return piuo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (piuo *PluginInstallUpdateOne) SetTenant(t *Tenant) *PluginInstallUpdateOne {
	return piuo.SetTenantID(t.ID)
}

// Mutation returns the PluginInstallMutation object of the builder.
func (piuo *PluginInstallUpdateOne) Mutation() *PluginInstallMutation {
	return piuo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (piuo *PluginInstallUpdateOne) ClearTenant() *PluginInstallUpdateOne {
	piuo.mutation.ClearTenant()
	return piuo
}

// Where appends a list predicates to the PluginInstallUpdate builder.
func (piuo *PluginInstallUpdateOne) Where(ps ...predicate.PluginInstall) *PluginInstallUpdateOne {
	piuo.mutation.Where(ps...)
	return piuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (piuo *PluginInstallUpdateOne) Select(field string, fields ...string) *PluginInstallUpdateOne {
	piuo.fields = append([]string{field}, fields...)
	return piuo
}

// Save executes the query and returns the updated PluginInstall entity.
func (piuo *PluginInstallUpdateOne) Save(ctx context.Context) (*PluginInstall, error) {
	return withHooks(ctx, piuo.sqlSave, piuo.mutation, piuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (piuo *PluginInstallUpdateOne) SaveX(ctx context.Context) *PluginInstall {
	node, err := piuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (piuo *PluginInstallUpdateOne) Exec(ctx context.Context) error {
	_, err := piuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (piuo *PluginInstallUpdateOne) ExecX(ctx context.Context) {
	if err := piuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (piuo *PluginInstallUpdateOne) check() error {
	if piuo.mutation.TenantCleared() && len(piuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginInstall.tenant"`)
	}
	return nil
}

func (piuo *PluginInstallUpdateOne) sqlSave(ctx context.Context) (_node *PluginInstall, err error) {
	if err := piuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugininstall.Table, plugininstall.Columns, sqlgraph.NewFieldSpec(plugininstall.FieldID, field.TypeString))
	id, ok := piuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginInstall.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := piuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugininstall.FieldID)
		for _, f := range fields {
			if !plugininstall.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plugininstall.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := piuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := piuo.mutation.PluginName(); ok {
		_spec.SetField(plugininstall.FieldPluginName, field.TypeString, value)
	}
	if value, ok := piuo.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstall.FieldInstalledAt, field.TypeTime, value)
	}
	if value, ok := piuo.mutation.Permissions(); ok {
		_spec.SetField(plugininstall.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := piuo.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstall.FieldPermissions, value)
		})
	}
	if piuo.mutation.PermissionsCleared() {
		_spec.ClearField(plugininstall.FieldPermissions, field.TypeJSON)
	}
	if piuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plugininstall.TenantTable,
			Columns: []string{plugininstall.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = piuo.schemaConfig.PluginInstall
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := piuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   plugininstall.TenantTable,
			Columns: []string{plugininstall.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = piuo.schemaConfig.PluginInstall
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = piuo.schemaConfig.PluginInstall
	ctx = internal.NewSchemaConfigContext(ctx, piuo.schemaConfig)
	_node = &PluginInstall{config: piuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, piuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugininstall.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	piuo.mutation.done = true
	return _node, nil
}
