// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
)

// PluginInstallDelete is the builder for deleting a PluginInstall entity.
type PluginInstallDelete struct {
	config
	hooks    []Hook
	mutation *PluginInstallMutation
}

// Where appends a list predicates to the PluginInstallDelete builder.
func (pid *PluginInstallDelete) Where(ps ...predicate.PluginInstall) *PluginInstallDelete {
	pid.mutation.Where(ps...)
	return pid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pid *PluginInstallDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pid.sqlExec, pid.mutation, pid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pid *PluginInstallDelete) ExecX(ctx context.Context) int {
	n, err := pid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pid *PluginInstallDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(plugininstall.Table, sqlgraph.NewFieldSpec(plugininstall.FieldID, field.TypeString))
	_spec.Node.Schema = pid.schemaConfig.PluginInstall
	ctx = internal.NewSchemaConfigContext(ctx, pid.schemaConfig)
	if ps := pid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pid.mutation.done = true
	return affected, err
}

// PluginInstallDeleteOne is the builder for deleting a single PluginInstall entity.
type PluginInstallDeleteOne struct {
	pid *PluginInstallDelete
}

// Where appends a list predicates to the PluginInstallDelete builder.
func (pido *PluginInstallDeleteOne) Where(ps ...predicate.PluginInstall) *PluginInstallDeleteOne {
	pido.pid.mutation.Where(ps...)
	return pido
}

// Exec executes the deletion query.
func (pido *PluginInstallDeleteOne) Exec(ctx context.Context) error {
	n, err := pido.pid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{plugininstall.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pido *PluginInstallDeleteOne) ExecX(ctx context.Context) {
	if err := pido.Exec(ctx); err != nil {
		panic(err)
	}
}
