// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/refreshtoken"
)

// RefreshTokenUpdate is the builder for updating RefreshToken entities.
type RefreshTokenUpdate struct {
	config
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtu *RefreshTokenUpdate) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdate {
	rtu.mutation.Where(ps...)
	return rtu
}

// SetUserID sets the "user_id" field.
func (rtu *RefreshTokenUpdate) SetUserID(s string) *RefreshTokenUpdate {
	rtu.mutation.SetUserID(s)
	return rtu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableUserID(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetUserID(*s)
	}
	return rtu
}

// SetTenantID sets the "tenant_id" field.
func (rtu *RefreshTokenUpdate) SetTenantID(s string) *RefreshTokenUpdate {
	rtu.mutation.SetTenantID(s)
	return rtu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableTenantID(s *string) *RefreshTokenUpdate {
	if s != nil {
		rtu.SetTenantID(*s)
	}
	return rtu
}

// SetExpiresAt sets the "expires_at" field.
func (rtu *RefreshTokenUpdate) SetExpiresAt(t time.Time) *RefreshTokenUpdate {
	rtu.mutation.SetExpiresAt(t)
	return rtu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableExpiresAt(t *time.Time) *RefreshTokenUpdate {
	if t != nil {
		rtu.SetExpiresAt(*t)
	}
	return rtu
}

// SetRevoked sets the "revoked" field.
func (rtu *RefreshTokenUpdate) SetRevoked(b bool) *RefreshTokenUpdate {
	rtu.mutation.SetRevoked(b)
	return rtu
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (rtu *RefreshTokenUpdate) SetNillableRevoked(b *bool) *RefreshTokenUpdate {
	if b != nil {
		rtu.SetRevoked(*b)
	}
	return rtu
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtu *RefreshTokenUpdate) Mutation() *RefreshTokenMutation {
	return rtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rtu *RefreshTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rtu.sqlSave, rtu.mutation, rtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := rtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rtu *RefreshTokenUpdate) Exec(ctx context.Context) error {
	_, err := rtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtu *RefreshTokenUpdate) ExecX(ctx context.Context) {
	if err := rtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtu *RefreshTokenUpdate) check() error {
	if v, ok := rtu.mutation.UserID(); ok {
		if err := refreshtoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.user_id": %w`, err)}
		}
	}
	if v, ok := rtu.mutation.TenantID(); ok {
		if err := refreshtoken.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (rtu *RefreshTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeString))
	if ps := rtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtu.mutation.UserID(); ok {
		_spec.SetField(refreshtoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := rtu.mutation.TenantID(); ok {
		_spec.SetField(refreshtoken.FieldTenantID, field.TypeString, value)
	}
	if value, ok := rtu.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := rtu.mutation.Revoked(); ok {
		_spec.SetField(refreshtoken.FieldRevoked, field.TypeBool, value)
	}
	_spec.Node.Schema = rtu.schemaConfig.RefreshToken
	ctx = internal.NewSchemaConfigContext(ctx, rtu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, rtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rtu.mutation.done = true
	return n, nil
}

// RefreshTokenUpdateOne is the builder for updating a single RefreshToken entity.
type RefreshTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefreshTokenMutation
}

// SetUserID sets the "user_id" field.
func (rtuo *RefreshTokenUpdateOne) SetUserID(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetUserID(s)
	return rtuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableUserID(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetUserID(*s)
	}
	return rtuo
}

// SetTenantID sets the "tenant_id" field.
func (rtuo *RefreshTokenUpdateOne) SetTenantID(s string) *RefreshTokenUpdateOne {
	rtuo.mutation.SetTenantID(s)
	return rtuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableTenantID(s *string) *RefreshTokenUpdateOne {
	if s != nil {
		rtuo.SetTenantID(*s)
	}
	return rtuo
}

// SetExpiresAt sets the "expires_at" field.
func (rtuo *RefreshTokenUpdateOne) SetExpiresAt(t time.Time) *RefreshTokenUpdateOne {
	rtuo.mutation.SetExpiresAt(t)
	return rtuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableExpiresAt(t *time.Time) *RefreshTokenUpdateOne {
	if t != nil {
		rtuo.SetExpiresAt(*t)
	}
	return rtuo
}

// SetRevoked sets the "revoked" field.
func (rtuo *RefreshTokenUpdateOne) SetRevoked(b bool) *RefreshTokenUpdateOne {
	rtuo.mutation.SetRevoked(b)
	return rtuo
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (rtuo *RefreshTokenUpdateOne) SetNillableRevoked(b *bool) *RefreshTokenUpdateOne {
	if b != nil {
		rtuo.SetRevoked(*b)
	}
	return rtuo
}

// Mutation returns the RefreshTokenMutation object of the builder.
func (rtuo *RefreshTokenUpdateOne) Mutation() *RefreshTokenMutation {
	return rtuo.mutation
}

// Where appends a list predicates to the RefreshTokenUpdate builder.
func (rtuo *RefreshTokenUpdateOne) Where(ps ...predicate.RefreshToken) *RefreshTokenUpdateOne {
	rtuo.mutation.Where(ps...)
	return rtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rtuo *RefreshTokenUpdateOne) Select(field string, fields ...string) *RefreshTokenUpdateOne {
	rtuo.fields = append([]string{field}, fields...)
	return rtuo
}

// Save executes the query and returns the updated RefreshToken entity.
func (rtuo *RefreshTokenUpdateOne) Save(ctx context.Context) (*RefreshToken, error) {
	return withHooks(ctx, rtuo.sqlSave, rtuo.mutation, rtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) SaveX(ctx context.Context) *RefreshToken {
	node, err := rtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rtuo *RefreshTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := rtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rtuo *RefreshTokenUpdateOne) ExecX(ctx context.Context) {
	if err := rtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rtuo *RefreshTokenUpdateOne) check() error {
	if v, ok := rtuo.mutation.UserID(); ok {
		if err := refreshtoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.user_id": %w`, err)}
		}
	}
	if v, ok := rtuo.mutation.TenantID(); ok {
		if err := refreshtoken.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "RefreshToken.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (rtuo *RefreshTokenUpdateOne) sqlSave(ctx context.Context) (_node *RefreshToken, err error) {
	if err := rtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refreshtoken.Table, refreshtoken.Columns, sqlgraph.NewFieldSpec(refreshtoken.FieldID, field.TypeString))
	id, ok := rtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefreshToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refreshtoken.FieldID)
		for _, f := range fields {
			if !refreshtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refreshtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rtuo.mutation.UserID(); ok {
		_spec.SetField(refreshtoken.FieldUserID, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.TenantID(); ok {
		_spec.SetField(refreshtoken.FieldTenantID, field.TypeString, value)
	}
	if value, ok := rtuo.mutation.ExpiresAt(); ok {
		_spec.SetField(refreshtoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := rtuo.mutation.Revoked(); ok {
		_spec.SetField(refreshtoken.FieldRevoked, field.TypeBool, value)
	}
	_spec.Node.Schema = rtuo.schemaConfig.RefreshToken
	ctx = internal.NewSchemaConfigContext(ctx, rtuo.schemaConfig)
	_node = &RefreshToken{config: rtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refreshtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rtuo.mutation.done = true
	return _node, nil
}
