// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/msrsiddik/apicorex-identity/ent/role"
	"github.com/msrsiddik/apicorex-identity/ent/rolepermission"
)

// RolePermission is the model entity for the RolePermission schema.
type RolePermission struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID string `json:"role_id,omitempty"`
	// Permission holds the value of the "permission" field.
	Permission string `json:"permission,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RolePermissionQuery when eager-loading is set.
	Edges        RolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RolePermissionEdges holds the relations/edges for other nodes in the graph.
type RolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RolePermissionEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolepermission.FieldID, rolepermission.FieldRoleID, rolepermission.FieldPermission:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RolePermission fields.
func (rp *RolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolepermission.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rp.ID = value.String
			}
		case rolepermission.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				rp.RoleID = value.String
			}
		case rolepermission.FieldPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission", values[i])
			} else if value.Valid {
				rp.Permission = value.String
			}
		default:
			rp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RolePermission.
// This includes values selected through modifiers, order, etc.
func (rp *RolePermission) Value(name string) (ent.Value, error) {
	return rp.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the RolePermission entity.
func (rp *RolePermission) QueryRole() *RoleQuery {
	return NewRolePermissionClient(rp.config).QueryRole(rp)
}

// Update returns a builder for updating this RolePermission.
// Note that you need to call RolePermission.Unwrap() before calling this method if this RolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (rp *RolePermission) Update() *RolePermissionUpdateOne {
	return NewRolePermissionClient(rp.config).UpdateOne(rp)
}

// Unwrap unwraps the RolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rp *RolePermission) Unwrap() *RolePermission {
	_tx, ok := rp.config.driver.(*txDriver)
	if !ok {
		panic("ent: RolePermission is not a transactional entity")
	}
	rp.config.driver = _tx.drv
	return rp
}

// String implements the fmt.Stringer.
func (rp *RolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("RolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rp.ID))
	builder.WriteString("role_id=")
	builder.WriteString(rp.RoleID)
	builder.WriteString(", ")
	builder.WriteString("permission=")
	builder.WriteString(rp.Permission)
	builder.WriteByte(')')
	return builder.String()
}

// RolePermissions is a parsable slice of RolePermission.
type RolePermissions []*RolePermission
