// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/msrsiddik/apicorex-identity/ent/branch"
	"github.com/msrsiddik/apicorex-identity/ent/devicetoken"
	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/pluginmigrationhistory"
	"github.com/msrsiddik/apicorex-identity/ent/role"
	"github.com/msrsiddik/apicorex-identity/ent/schema"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
	"github.com/msrsiddik/apicorex-identity/ent/tenantuser"
	"github.com/msrsiddik/apicorex-identity/ent/user"
	"github.com/msrsiddik/apicorex-identity/ent/userprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescStatus is the schema descriptor for status field.
	branchDescStatus := branchFields[4].Descriptor()
	// branch.DefaultStatus holds the default value on creation for the status field.
	branch.DefaultStatus = branchDescStatus.Default.(string)
	// branchDescCreatedAt is the schema descriptor for created_at field.
	branchDescCreatedAt := branchFields[5].Descriptor()
	// branch.DefaultCreatedAt holds the default value on creation for the created_at field.
	branch.DefaultCreatedAt = branchDescCreatedAt.Default.(func() time.Time)
	devicetokenFields := schema.DeviceToken{}.Fields()
	_ = devicetokenFields
	// devicetokenDescTokenHash is the schema descriptor for token_hash field.
	devicetokenDescTokenHash := devicetokenFields[1].Descriptor()
	// devicetoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	devicetoken.TokenHashValidator = devicetokenDescTokenHash.Validators[0].(func(string) error)
	// devicetokenDescUserID is the schema descriptor for user_id field.
	devicetokenDescUserID := devicetokenFields[2].Descriptor()
	// devicetoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	devicetoken.UserIDValidator = devicetokenDescUserID.Validators[0].(func(string) error)
	// devicetokenDescTenantID is the schema descriptor for tenant_id field.
	devicetokenDescTenantID := devicetokenFields[3].Descriptor()
	// devicetoken.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	devicetoken.TenantIDValidator = devicetokenDescTenantID.Validators[0].(func(string) error)
	// devicetokenDescDeviceName is the schema descriptor for device_name field.
	devicetokenDescDeviceName := devicetokenFields[5].Descriptor()
	// devicetoken.DefaultDeviceName holds the default value on creation for the device_name field.
	devicetoken.DefaultDeviceName = devicetokenDescDeviceName.Default.(string)
	// devicetokenDescCreatedAt is the schema descriptor for created_at field.
	devicetokenDescCreatedAt := devicetokenFields[6].Descriptor()
	// devicetoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicetoken.DefaultCreatedAt = devicetokenDescCreatedAt.Default.(func() time.Time)
	plugininstallFields := schema.PluginInstall{}.Fields()
	_ = plugininstallFields
	// plugininstallDescInstalledAt is the schema descriptor for installed_at field.
	plugininstallDescInstalledAt := plugininstallFields[3].Descriptor()
	// plugininstall.DefaultInstalledAt holds the default value on creation for the installed_at field.
	plugininstall.DefaultInstalledAt = plugininstallDescInstalledAt.Default.(func() time.Time)
	pluginmigrationhistoryFields := schema.PluginMigrationHistory{}.Fields()
	_ = pluginmigrationhistoryFields
	// pluginmigrationhistoryDescStatus is the schema descriptor for status field.
	pluginmigrationhistoryDescStatus := pluginmigrationhistoryFields[5].Descriptor()
	// pluginmigrationhistory.DefaultStatus holds the default value on creation for the status field.
	pluginmigrationhistory.DefaultStatus = pluginmigrationhistoryDescStatus.Default.(string)
	// pluginmigrationhistoryDescAppliedAt is the schema descriptor for applied_at field.
	pluginmigrationhistoryDescAppliedAt := pluginmigrationhistoryFields[6].Descriptor()
	// pluginmigrationhistory.DefaultAppliedAt holds the default value on creation for the applied_at field.
	pluginmigrationhistory.DefaultAppliedAt = pluginmigrationhistoryDescAppliedAt.Default.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[4].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[5].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescPlan is the schema descriptor for plan field.
	tenantDescPlan := tenantFields[3].Descriptor()
	// tenant.DefaultPlan holds the default value on creation for the plan field.
	tenant.DefaultPlan = tenantDescPlan.Default.(string)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[4].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	tenantuserFields := schema.TenantUser{}.Fields()
	_ = tenantuserFields
	// tenantuserDescStatus is the schema descriptor for status field.
	tenantuserDescStatus := tenantuserFields[5].Descriptor()
	// tenantuser.DefaultStatus holds the default value on creation for the status field.
	tenantuser.DefaultStatus = tenantuserDescStatus.Default.(string)
	// tenantuserDescCreatedAt is the schema descriptor for created_at field.
	tenantuserDescCreatedAt := tenantuserFields[6].Descriptor()
	// tenantuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantuser.DefaultCreatedAt = tenantuserDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsPlatformAdmin is the schema descriptor for is_platform_admin field.
	userDescIsPlatformAdmin := userFields[4].Descriptor()
	// user.DefaultIsPlatformAdmin holds the default value on creation for the is_platform_admin field.
	user.DefaultIsPlatformAdmin = userDescIsPlatformAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userprofileFields := schema.UserProfile{}.Fields()
	_ = userprofileFields
	// userprofileDescSystemRole is the schema descriptor for system_role field.
	userprofileDescSystemRole := userprofileFields[4].Descriptor()
	// userprofile.DefaultSystemRole holds the default value on creation for the system_role field.
	userprofile.DefaultSystemRole = userprofileDescSystemRole.Default.(string)
	// userprofileDescPinHash is the schema descriptor for pin_hash field.
	userprofileDescPinHash := userprofileFields[5].Descriptor()
	// userprofile.DefaultPinHash holds the default value on creation for the pin_hash field.
	userprofile.DefaultPinHash = userprofileDescPinHash.Default.(string)
	// userprofileDescCreatedAt is the schema descriptor for created_at field.
	userprofileDescCreatedAt := userprofileFields[6].Descriptor()
	// userprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	userprofile.DefaultCreatedAt = userprofileDescCreatedAt.Default.(func() time.Time)
}
