// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/msrsiddik/apicorex-identity/ent/plugininstall"
	"github.com/msrsiddik/apicorex-identity/ent/pluginmigrationhistory"
	"github.com/msrsiddik/apicorex-identity/ent/refreshtoken"
	"github.com/msrsiddik/apicorex-identity/ent/schema"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
	"github.com/msrsiddik/apicorex-identity/ent/tenantuser"
	"github.com/msrsiddik/apicorex-identity/ent/user"
	"github.com/msrsiddik/apicorex-identity/ent/userprofile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	plugininstallFields := schema.PluginInstall{}.Fields()
	_ = plugininstallFields
	// plugininstallDescInstalledAt is the schema descriptor for installed_at field.
	plugininstallDescInstalledAt := plugininstallFields[3].Descriptor()
	// plugininstall.DefaultInstalledAt holds the default value on creation for the installed_at field.
	plugininstall.DefaultInstalledAt = plugininstallDescInstalledAt.Default.(func() time.Time)
	pluginmigrationhistoryFields := schema.PluginMigrationHistory{}.Fields()
	_ = pluginmigrationhistoryFields
	// pluginmigrationhistoryDescStatus is the schema descriptor for status field.
	pluginmigrationhistoryDescStatus := pluginmigrationhistoryFields[5].Descriptor()
	// pluginmigrationhistory.DefaultStatus holds the default value on creation for the status field.
	pluginmigrationhistory.DefaultStatus = pluginmigrationhistoryDescStatus.Default.(string)
	// pluginmigrationhistoryDescAppliedAt is the schema descriptor for applied_at field.
	pluginmigrationhistoryDescAppliedAt := pluginmigrationhistoryFields[6].Descriptor()
	// pluginmigrationhistory.DefaultAppliedAt holds the default value on creation for the applied_at field.
	pluginmigrationhistory.DefaultAppliedAt = pluginmigrationhistoryDescAppliedAt.Default.(func() time.Time)
	refreshtokenFields := schema.RefreshToken{}.Fields()
	_ = refreshtokenFields
	// refreshtokenDescUserID is the schema descriptor for user_id field.
	refreshtokenDescUserID := refreshtokenFields[1].Descriptor()
	// refreshtoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	refreshtoken.UserIDValidator = refreshtokenDescUserID.Validators[0].(func(string) error)
	// refreshtokenDescTenantID is the schema descriptor for tenant_id field.
	refreshtokenDescTenantID := refreshtokenFields[2].Descriptor()
	// refreshtoken.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	refreshtoken.TenantIDValidator = refreshtokenDescTenantID.Validators[0].(func(string) error)
	// refreshtokenDescRevoked is the schema descriptor for revoked field.
	refreshtokenDescRevoked := refreshtokenFields[4].Descriptor()
	// refreshtoken.DefaultRevoked holds the default value on creation for the revoked field.
	refreshtoken.DefaultRevoked = refreshtokenDescRevoked.Default.(bool)
	// refreshtokenDescCreatedAt is the schema descriptor for created_at field.
	refreshtokenDescCreatedAt := refreshtokenFields[5].Descriptor()
	// refreshtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	refreshtoken.DefaultCreatedAt = refreshtokenDescCreatedAt.Default.(func() time.Time)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescPlan is the schema descriptor for plan field.
	tenantDescPlan := tenantFields[3].Descriptor()
	// tenant.DefaultPlan holds the default value on creation for the plan field.
	tenant.DefaultPlan = tenantDescPlan.Default.(string)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantFields[4].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(string)
	tenantuserFields := schema.TenantUser{}.Fields()
	_ = tenantuserFields
	// tenantuserDescRole is the schema descriptor for role field.
	tenantuserDescRole := tenantuserFields[3].Descriptor()
	// tenantuser.DefaultRole holds the default value on creation for the role field.
	tenantuser.DefaultRole = tenantuserDescRole.Default.(string)
	// tenantuserDescCreatedAt is the schema descriptor for created_at field.
	tenantuserDescCreatedAt := tenantuserFields[4].Descriptor()
	// tenantuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantuser.DefaultCreatedAt = tenantuserDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsPlatformAdmin is the schema descriptor for is_platform_admin field.
	userDescIsPlatformAdmin := userFields[3].Descriptor()
	// user.DefaultIsPlatformAdmin holds the default value on creation for the is_platform_admin field.
	user.DefaultIsPlatformAdmin = userDescIsPlatformAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userprofileFields := schema.UserProfile{}.Fields()
	_ = userprofileFields
	// userprofileDescSystemRole is the schema descriptor for system_role field.
	userprofileDescSystemRole := userprofileFields[4].Descriptor()
	// userprofile.DefaultSystemRole holds the default value on creation for the system_role field.
	userprofile.DefaultSystemRole = userprofileDescSystemRole.Default.(string)
	// userprofileDescCreatedAt is the schema descriptor for created_at field.
	userprofileDescCreatedAt := userprofileFields[5].Descriptor()
	// userprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	userprofile.DefaultCreatedAt = userprofileDescCreatedAt.Default.(func() time.Time)
}
