// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/tenantuser"
)

// TenantUserDelete is the builder for deleting a TenantUser entity.
type TenantUserDelete struct {
	config
	hooks    []Hook
	mutation *TenantUserMutation
}

// Where appends a list predicates to the TenantUserDelete builder.
func (tud *TenantUserDelete) Where(ps ...predicate.TenantUser) *TenantUserDelete {
	tud.mutation.Where(ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TenantUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tud.sqlExec, tud.mutation, tud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TenantUserDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TenantUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantuser.Table, sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeString))
	_spec.Node.Schema = tud.schemaConfig.TenantUser
	ctx = internal.NewSchemaConfigContext(ctx, tud.schemaConfig)
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tud.mutation.done = true
	return affected, err
}

// TenantUserDeleteOne is the builder for deleting a single TenantUser entity.
type TenantUserDeleteOne struct {
	tud *TenantUserDelete
}

// Where appends a list predicates to the TenantUserDelete builder.
func (tudo *TenantUserDeleteOne) Where(ps ...predicate.TenantUser) *TenantUserDeleteOne {
	tudo.tud.mutation.Where(ps...)
	return tudo
}

// Exec executes the deletion query.
func (tudo *TenantUserDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TenantUserDeleteOne) ExecX(ctx context.Context) {
	if err := tudo.Exec(ctx); err != nil {
		panic(err)
	}
}
