// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
	"github.com/msrsiddik/apicorex-identity/ent/tenant"
	"github.com/msrsiddik/apicorex-identity/ent/tenantuser"
	"github.com/msrsiddik/apicorex-identity/ent/user"
)

// TenantUserUpdate is the builder for updating TenantUser entities.
type TenantUserUpdate struct {
	config
	hooks    []Hook
	mutation *TenantUserMutation
}

// Where appends a list predicates to the TenantUserUpdate builder.
func (tuu *TenantUserUpdate) Where(ps ...predicate.TenantUser) *TenantUserUpdate {
	tuu.mutation.Where(ps...)
	return tuu
}

// SetUserID sets the "user_id" field.
func (tuu *TenantUserUpdate) SetUserID(s string) *TenantUserUpdate {
	tuu.mutation.SetUserID(s)
	return tuu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tuu *TenantUserUpdate) SetNillableUserID(s *string) *TenantUserUpdate {
	if s != nil {
		tuu.SetUserID(*s)
	}
	return tuu
}

// SetTenantID sets the "tenant_id" field.
func (tuu *TenantUserUpdate) SetTenantID(s string) *TenantUserUpdate {
	tuu.mutation.SetTenantID(s)
	return tuu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tuu *TenantUserUpdate) SetNillableTenantID(s *string) *TenantUserUpdate {
	if s != nil {
		tuu.SetTenantID(*s)
	}
	return tuu
}

// SetBranchID sets the "branch_id" field.
func (tuu *TenantUserUpdate) SetBranchID(s string) *TenantUserUpdate {
	tuu.mutation.SetBranchID(s)
	return tuu
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (tuu *TenantUserUpdate) SetNillableBranchID(s *string) *TenantUserUpdate {
	if s != nil {
		tuu.SetBranchID(*s)
	}
	return tuu
}

// SetRoleID sets the "role_id" field.
func (tuu *TenantUserUpdate) SetRoleID(s string) *TenantUserUpdate {
	tuu.mutation.SetRoleID(s)
	return tuu
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (tuu *TenantUserUpdate) SetNillableRoleID(s *string) *TenantUserUpdate {
	if s != nil {
		tuu.SetRoleID(*s)
	}
	return tuu
}

// SetIsDefault sets the "is_default" field.
func (tuu *TenantUserUpdate) SetIsDefault(b bool) *TenantUserUpdate {
	tuu.mutation.SetIsDefault(b)
	return tuu
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (tuu *TenantUserUpdate) SetNillableIsDefault(b *bool) *TenantUserUpdate {
	if b != nil {
		tuu.SetIsDefault(*b)
	}
	return tuu
}

// SetUser sets the "user" edge to the User entity.
func (tuu *TenantUserUpdate) SetUser(u *User) *TenantUserUpdate {
	return tuu.SetUserID(u.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (tuu *TenantUserUpdate) SetTenant(t *Tenant) *TenantUserUpdate {
	return tuu.SetTenantID(t.ID)
}

// Mutation returns the TenantUserMutation object of the builder.
func (tuu *TenantUserUpdate) Mutation() *TenantUserMutation {
	return tuu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tuu *TenantUserUpdate) ClearUser() *TenantUserUpdate {
	tuu.mutation.ClearUser()
	return tuu
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (tuu *TenantUserUpdate) ClearTenant() *TenantUserUpdate {
	tuu.mutation.ClearTenant()
	return tuu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tuu *TenantUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tuu.sqlSave, tuu.mutation, tuu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuu *TenantUserUpdate) SaveX(ctx context.Context) int {
	affected, err := tuu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tuu *TenantUserUpdate) Exec(ctx context.Context) error {
	_, err := tuu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuu *TenantUserUpdate) ExecX(ctx context.Context) {
	if err := tuu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuu *TenantUserUpdate) check() error {
	if tuu.mutation.UserCleared() && len(tuu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.user"`)
	}
	if tuu.mutation.TenantCleared() && len(tuu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.tenant"`)
	}
	return nil
}

func (tuu *TenantUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tuu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantuser.Table, tenantuser.Columns, sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeString))
	if ps := tuu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuu.mutation.BranchID(); ok {
		_spec.SetField(tenantuser.FieldBranchID, field.TypeString, value)
	}
	if value, ok := tuu.mutation.RoleID(); ok {
		_spec.SetField(tenantuser.FieldRoleID, field.TypeString, value)
	}
	if value, ok := tuu.mutation.IsDefault(); ok {
		_spec.SetField(tenantuser.FieldIsDefault, field.TypeBool, value)
	}
	if tuu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuu.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuu.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuu.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuu.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = tuu.schemaConfig.TenantUser
	ctx = internal.NewSchemaConfigContext(ctx, tuu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, tuu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tuu.mutation.done = true
	return n, nil
}

// TenantUserUpdateOne is the builder for updating a single TenantUser entity.
type TenantUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantUserMutation
}

// SetUserID sets the "user_id" field.
func (tuuo *TenantUserUpdateOne) SetUserID(s string) *TenantUserUpdateOne {
	tuuo.mutation.SetUserID(s)
	return tuuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tuuo *TenantUserUpdateOne) SetNillableUserID(s *string) *TenantUserUpdateOne {
	if s != nil {
		tuuo.SetUserID(*s)
	}
	return tuuo
}

// SetTenantID sets the "tenant_id" field.
func (tuuo *TenantUserUpdateOne) SetTenantID(s string) *TenantUserUpdateOne {
	tuuo.mutation.SetTenantID(s)
	return tuuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tuuo *TenantUserUpdateOne) SetNillableTenantID(s *string) *TenantUserUpdateOne {
	if s != nil {
		tuuo.SetTenantID(*s)
	}
	return tuuo
}

// SetBranchID sets the "branch_id" field.
func (tuuo *TenantUserUpdateOne) SetBranchID(s string) *TenantUserUpdateOne {
	tuuo.mutation.SetBranchID(s)
	return tuuo
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (tuuo *TenantUserUpdateOne) SetNillableBranchID(s *string) *TenantUserUpdateOne {
	if s != nil {
		tuuo.SetBranchID(*s)
	}
	return tuuo
}

// SetRoleID sets the "role_id" field.
func (tuuo *TenantUserUpdateOne) SetRoleID(s string) *TenantUserUpdateOne {
	tuuo.mutation.SetRoleID(s)
	return tuuo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (tuuo *TenantUserUpdateOne) SetNillableRoleID(s *string) *TenantUserUpdateOne {
	if s != nil {
		tuuo.SetRoleID(*s)
	}
	return tuuo
}

// SetIsDefault sets the "is_default" field.
func (tuuo *TenantUserUpdateOne) SetIsDefault(b bool) *TenantUserUpdateOne {
	tuuo.mutation.SetIsDefault(b)
	return tuuo
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (tuuo *TenantUserUpdateOne) SetNillableIsDefault(b *bool) *TenantUserUpdateOne {
	if b != nil {
		tuuo.SetIsDefault(*b)
	}
	return tuuo
}

// SetUser sets the "user" edge to the User entity.
func (tuuo *TenantUserUpdateOne) SetUser(u *User) *TenantUserUpdateOne {
	return tuuo.SetUserID(u.ID)
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (tuuo *TenantUserUpdateOne) SetTenant(t *Tenant) *TenantUserUpdateOne {
	return tuuo.SetTenantID(t.ID)
}

// Mutation returns the TenantUserMutation object of the builder.
func (tuuo *TenantUserUpdateOne) Mutation() *TenantUserMutation {
	return tuuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (tuuo *TenantUserUpdateOne) ClearUser() *TenantUserUpdateOne {
	tuuo.mutation.ClearUser()
	return tuuo
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (tuuo *TenantUserUpdateOne) ClearTenant() *TenantUserUpdateOne {
	tuuo.mutation.ClearTenant()
	return tuuo
}

// Where appends a list predicates to the TenantUserUpdate builder.
func (tuuo *TenantUserUpdateOne) Where(ps ...predicate.TenantUser) *TenantUserUpdateOne {
	tuuo.mutation.Where(ps...)
	return tuuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuuo *TenantUserUpdateOne) Select(field string, fields ...string) *TenantUserUpdateOne {
	tuuo.fields = append([]string{field}, fields...)
	return tuuo
}

// Save executes the query and returns the updated TenantUser entity.
func (tuuo *TenantUserUpdateOne) Save(ctx context.Context) (*TenantUser, error) {
	return withHooks(ctx, tuuo.sqlSave, tuuo.mutation, tuuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuuo *TenantUserUpdateOne) SaveX(ctx context.Context) *TenantUser {
	node, err := tuuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuuo *TenantUserUpdateOne) Exec(ctx context.Context) error {
	_, err := tuuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuuo *TenantUserUpdateOne) ExecX(ctx context.Context) {
	if err := tuuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuuo *TenantUserUpdateOne) check() error {
	if tuuo.mutation.UserCleared() && len(tuuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.user"`)
	}
	if tuuo.mutation.TenantCleared() && len(tuuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantUser.tenant"`)
	}
	return nil
}

func (tuuo *TenantUserUpdateOne) sqlSave(ctx context.Context) (_node *TenantUser, err error) {
	if err := tuuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantuser.Table, tenantuser.Columns, sqlgraph.NewFieldSpec(tenantuser.FieldID, field.TypeString))
	id, ok := tuuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantuser.FieldID)
		for _, f := range fields {
			if !tenantuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuuo.mutation.BranchID(); ok {
		_spec.SetField(tenantuser.FieldBranchID, field.TypeString, value)
	}
	if value, ok := tuuo.mutation.RoleID(); ok {
		_spec.SetField(tenantuser.FieldRoleID, field.TypeString, value)
	}
	if value, ok := tuuo.mutation.IsDefault(); ok {
		_spec.SetField(tenantuser.FieldIsDefault, field.TypeBool, value)
	}
	if tuuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuuo.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.UserTable,
			Columns: []string{tenantuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuuo.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuuo.schemaConfig.TenantUser
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantuser.TenantTable,
			Columns: []string{tenantuser.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeString),
			},
		}
		edge.Schema = tuuo.schemaConfig.TenantUser
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = tuuo.schemaConfig.TenantUser
	ctx = internal.NewSchemaConfigContext(ctx, tuuo.schemaConfig)
	_node = &TenantUser{config: tuuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuuo.mutation.done = true
	return _node, nil
}
