// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msrsiddik/apicorex-identity/ent/userprofile"
)

// UserProfileCreate is the builder for creating a UserProfile entity.
type UserProfileCreate struct {
	config
	mutation *UserProfileMutation
	hooks    []Hook
}

// SetFullName sets the "full_name" field.
func (upc *UserProfileCreate) SetFullName(s string) *UserProfileCreate {
	upc.mutation.SetFullName(s)
	return upc
}

// SetPhone sets the "phone" field.
func (upc *UserProfileCreate) SetPhone(s string) *UserProfileCreate {
	upc.mutation.SetPhone(s)
	return upc
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillablePhone(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetPhone(*s)
	}
	return upc
}

// SetJobTitle sets the "job_title" field.
func (upc *UserProfileCreate) SetJobTitle(s string) *UserProfileCreate {
	upc.mutation.SetJobTitle(s)
	return upc
}

// SetNillableJobTitle sets the "job_title" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableJobTitle(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetJobTitle(*s)
	}
	return upc
}

// SetSystemRole sets the "system_role" field.
func (upc *UserProfileCreate) SetSystemRole(s string) *UserProfileCreate {
	upc.mutation.SetSystemRole(s)
	return upc
}

// SetNillableSystemRole sets the "system_role" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableSystemRole(s *string) *UserProfileCreate {
	if s != nil {
		upc.SetSystemRole(*s)
	}
	return upc
}

// SetCreatedAt sets the "created_at" field.
func (upc *UserProfileCreate) SetCreatedAt(t time.Time) *UserProfileCreate {
	upc.mutation.SetCreatedAt(t)
	return upc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (upc *UserProfileCreate) SetNillableCreatedAt(t *time.Time) *UserProfileCreate {
	if t != nil {
		upc.SetCreatedAt(*t)
	}
	return upc
}

// SetID sets the "id" field.
func (upc *UserProfileCreate) SetID(s string) *UserProfileCreate {
	upc.mutation.SetID(s)
	return upc
}

// Mutation returns the UserProfileMutation object of the builder.
func (upc *UserProfileCreate) Mutation() *UserProfileMutation {
	return upc.mutation
}

// Save creates the UserProfile in the database.
func (upc *UserProfileCreate) Save(ctx context.Context) (*UserProfile, error) {
	upc.defaults()
	return withHooks(ctx, upc.sqlSave, upc.mutation, upc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UserProfileCreate) SaveX(ctx context.Context) *UserProfile {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UserProfileCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UserProfileCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upc *UserProfileCreate) defaults() {
	if _, ok := upc.mutation.SystemRole(); !ok {
		v := userprofile.DefaultSystemRole
		upc.mutation.SetSystemRole(v)
	}
	if _, ok := upc.mutation.CreatedAt(); !ok {
		v := userprofile.DefaultCreatedAt()
		upc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UserProfileCreate) check() error {
	if _, ok := upc.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "UserProfile.full_name"`)}
	}
	if _, ok := upc.mutation.SystemRole(); !ok {
		return &ValidationError{Name: "system_role", err: errors.New(`ent: missing required field "UserProfile.system_role"`)}
	}
	if _, ok := upc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserProfile.created_at"`)}
	}
	return nil
}

func (upc *UserProfileCreate) sqlSave(ctx context.Context) (*UserProfile, error) {
	if err := upc.check(); err != nil {
		return nil, err
	}
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserProfile.ID type: %T", _spec.ID.Value)
		}
	}
	upc.mutation.id = &_node.ID
	upc.mutation.done = true
	return _node, nil
}

func (upc *UserProfileCreate) createSpec() (*UserProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &UserProfile{config: upc.config}
		_spec = sqlgraph.NewCreateSpec(userprofile.Table, sqlgraph.NewFieldSpec(userprofile.FieldID, field.TypeString))
	)
	_spec.Schema = upc.schemaConfig.UserProfile
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := upc.mutation.FullName(); ok {
		_spec.SetField(userprofile.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := upc.mutation.Phone(); ok {
		_spec.SetField(userprofile.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := upc.mutation.JobTitle(); ok {
		_spec.SetField(userprofile.FieldJobTitle, field.TypeString, value)
		_node.JobTitle = value
	}
	if value, ok := upc.mutation.SystemRole(); ok {
		_spec.SetField(userprofile.FieldSystemRole, field.TypeString, value)
		_node.SystemRole = value
	}
	if value, ok := upc.mutation.CreatedAt(); ok {
		_spec.SetField(userprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UserProfileCreateBulk is the builder for creating many UserProfile entities in bulk.
type UserProfileCreateBulk struct {
	config
	err      error
	builders []*UserProfileCreate
}

// Save creates the UserProfile entities in the database.
func (upcb *UserProfileCreateBulk) Save(ctx context.Context) ([]*UserProfile, error) {
	if upcb.err != nil {
		return nil, upcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UserProfile, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UserProfileCreateBulk) SaveX(ctx context.Context) []*UserProfile {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UserProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UserProfileCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
