// Code generated by ent, DO NOT EDIT.

package plugininstall

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/msrsiddik/apicorex-identity/ent/internal"
	"github.com/msrsiddik/apicorex-identity/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldTenantID, v))
}

// PluginName applies equality check predicate on the "plugin_name" field. It's identical to PluginNameEQ.
func PluginName(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldPluginName, v))
}

// InstalledAt applies equality check predicate on the "installed_at" field. It's identical to InstalledAtEQ.
func InstalledAt(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldInstalledAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldContainsFold(FieldTenantID, v))
}

// PluginNameEQ applies the EQ predicate on the "plugin_name" field.
func PluginNameEQ(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldPluginName, v))
}

// PluginNameNEQ applies the NEQ predicate on the "plugin_name" field.
func PluginNameNEQ(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNEQ(FieldPluginName, v))
}

// PluginNameIn applies the In predicate on the "plugin_name" field.
func PluginNameIn(vs ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldIn(FieldPluginName, vs...))
}

// PluginNameNotIn applies the NotIn predicate on the "plugin_name" field.
func PluginNameNotIn(vs ...string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNotIn(FieldPluginName, vs...))
}

// PluginNameGT applies the GT predicate on the "plugin_name" field.
func PluginNameGT(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGT(FieldPluginName, v))
}

// PluginNameGTE applies the GTE predicate on the "plugin_name" field.
func PluginNameGTE(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGTE(FieldPluginName, v))
}

// PluginNameLT applies the LT predicate on the "plugin_name" field.
func PluginNameLT(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLT(FieldPluginName, v))
}

// PluginNameLTE applies the LTE predicate on the "plugin_name" field.
func PluginNameLTE(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLTE(FieldPluginName, v))
}

// PluginNameContains applies the Contains predicate on the "plugin_name" field.
func PluginNameContains(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldContains(FieldPluginName, v))
}

// PluginNameHasPrefix applies the HasPrefix predicate on the "plugin_name" field.
func PluginNameHasPrefix(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldHasPrefix(FieldPluginName, v))
}

// PluginNameHasSuffix applies the HasSuffix predicate on the "plugin_name" field.
func PluginNameHasSuffix(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldHasSuffix(FieldPluginName, v))
}

// PluginNameEqualFold applies the EqualFold predicate on the "plugin_name" field.
func PluginNameEqualFold(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEqualFold(FieldPluginName, v))
}

// PluginNameContainsFold applies the ContainsFold predicate on the "plugin_name" field.
func PluginNameContainsFold(v string) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldContainsFold(FieldPluginName, v))
}

// InstalledAtEQ applies the EQ predicate on the "installed_at" field.
func InstalledAtEQ(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldEQ(FieldInstalledAt, v))
}

// InstalledAtNEQ applies the NEQ predicate on the "installed_at" field.
func InstalledAtNEQ(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNEQ(FieldInstalledAt, v))
}

// InstalledAtIn applies the In predicate on the "installed_at" field.
func InstalledAtIn(vs ...time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldIn(FieldInstalledAt, vs...))
}

// InstalledAtNotIn applies the NotIn predicate on the "installed_at" field.
func InstalledAtNotIn(vs ...time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNotIn(FieldInstalledAt, vs...))
}

// InstalledAtGT applies the GT predicate on the "installed_at" field.
func InstalledAtGT(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGT(FieldInstalledAt, v))
}

// InstalledAtGTE applies the GTE predicate on the "installed_at" field.
func InstalledAtGTE(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldGTE(FieldInstalledAt, v))
}

// InstalledAtLT applies the LT predicate on the "installed_at" field.
func InstalledAtLT(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLT(FieldInstalledAt, v))
}

// InstalledAtLTE applies the LTE predicate on the "installed_at" field.
func InstalledAtLTE(v time.Time) predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldLTE(FieldInstalledAt, v))
}

// PermissionsIsNil applies the IsNil predicate on the "permissions" field.
func PermissionsIsNil() predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldIsNull(FieldPermissions))
}

// PermissionsNotNil applies the NotNil predicate on the "permissions" field.
func PermissionsNotNil() predicate.PluginInstall {
	return predicate.PluginInstall(sql.FieldNotNull(FieldPermissions))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.PluginInstall {
	return predicate.PluginInstall(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.PluginInstall
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.PluginInstall {
	return predicate.PluginInstall(func(s *sql.Selector) {
		step := newTenantStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Tenant
		step.Edge.Schema = schemaConfig.PluginInstall
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginInstall) predicate.PluginInstall {
	return predicate.PluginInstall(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginInstall) predicate.PluginInstall {
	return predicate.PluginInstall(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginInstall) predicate.PluginInstall {
	return predicate.PluginInstall(sql.NotPredicates(p))
}
