// Code generated by ent, DO NOT EDIT.

package tenant

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tenant type in the database.
	Label = "tenant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlan holds the string denoting the plan field in the database.
	FieldPlan = "plan"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSchemaName holds the string denoting the schema_name field in the database.
	FieldSchemaName = "schema_name"
	// EdgeTenantUsers holds the string denoting the tenant_users edge name in mutations.
	EdgeTenantUsers = "tenant_users"
	// EdgePluginInstalls holds the string denoting the plugin_installs edge name in mutations.
	EdgePluginInstalls = "plugin_installs"
	// Table holds the table name of the tenant in the database.
	Table = "tenants"
	// TenantUsersTable is the table that holds the tenant_users relation/edge.
	TenantUsersTable = "tenant_users"
	// TenantUsersInverseTable is the table name for the TenantUser entity.
	// It exists in this package in order to avoid circular dependency with the "tenantuser" package.
	TenantUsersInverseTable = "tenant_users"
	// TenantUsersColumn is the table column denoting the tenant_users relation/edge.
	TenantUsersColumn = "tenant_id"
	// PluginInstallsTable is the table that holds the plugin_installs relation/edge.
	PluginInstallsTable = "plugin_installs"
	// PluginInstallsInverseTable is the table name for the PluginInstall entity.
	// It exists in this package in order to avoid circular dependency with the "plugininstall" package.
	PluginInstallsInverseTable = "plugin_installs"
	// PluginInstallsColumn is the table column denoting the plugin_installs relation/edge.
	PluginInstallsColumn = "tenant_id"
)

// Columns holds all SQL columns for tenant fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldName,
	FieldPlan,
	FieldStatus,
	FieldSchemaName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlan holds the default value on creation for the "plan" field.
	DefaultPlan string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)

// OrderOption defines the ordering options for the Tenant queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlan orders the results by the plan field.
func ByPlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlan, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySchemaName orders the results by the schema_name field.
func BySchemaName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaName, opts...).ToFunc()
}

// ByTenantUsersCount orders the results by tenant_users count.
func ByTenantUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTenantUsersStep(), opts...)
	}
}

// ByTenantUsers orders the results by tenant_users terms.
func ByTenantUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPluginInstallsCount orders the results by plugin_installs count.
func ByPluginInstallsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPluginInstallsStep(), opts...)
	}
}

// ByPluginInstalls orders the results by plugin_installs terms.
func ByPluginInstalls(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginInstallsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TenantUsersTable, TenantUsersColumn),
	)
}
func newPluginInstallsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginInstallsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PluginInstallsTable, PluginInstallsColumn),
	)
}
