// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldIsPlatformAdmin holds the string denoting the is_platform_admin field in the database.
	FieldIsPlatformAdmin = "is_platform_admin"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTenantUsers holds the string denoting the tenant_users edge name in mutations.
	EdgeTenantUsers = "tenant_users"
	// Table holds the table name of the user in the database.
	Table = "users"
	// TenantUsersTable is the table that holds the tenant_users relation/edge.
	TenantUsersTable = "tenant_users"
	// TenantUsersInverseTable is the table name for the TenantUser entity.
	// It exists in this package in order to avoid circular dependency with the "tenantuser" package.
	TenantUsersInverseTable = "tenant_users"
	// TenantUsersColumn is the table column denoting the tenant_users relation/edge.
	TenantUsersColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPasswordHash,
	FieldIsPlatformAdmin,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsPlatformAdmin holds the default value on creation for the "is_platform_admin" field.
	DefaultIsPlatformAdmin bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByIsPlatformAdmin orders the results by the is_platform_admin field.
func ByIsPlatformAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPlatformAdmin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTenantUsersCount orders the results by tenant_users count.
func ByTenantUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTenantUsersStep(), opts...)
	}
}

// ByTenantUsers orders the results by tenant_users terms.
func ByTenantUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TenantUsersTable, TenantUsersColumn),
	)
}
